//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace JJWBSService.Modes
{
	/// <summary>
	/// 实体类NPS_BOQ。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("NPS_BOQ")]
	[Serializable]
	public partial class NPS_BOQ : Entity
	{
		#region Model
		private Guid _ID;
		private string _Code;
		private string _Title;
		private string _TableName;
		private Guid? _BizAreaId;
		private int? _Sequ;
		private int? _Status;
		private Guid? _RegHumId;
		private string _RegHumName;
		private DateTime? _RegDate;
		private Guid? _RegPosiId;
		private Guid? _RegDeptId;
		private Guid? _EpsProjId;
		private Guid? _RecycleHumId;
		private Guid? _UpdHumId;
		private string _UpdHumName;
		private DateTime? _UpdDate;
		private Guid? _ApprHumId;
		private string _ApprHumName;
		private DateTime? _ApprDate;
		private string _Remark;
		private Guid? _OwnProjId;
		private string _OwnProjName;
		private string _EpsProjCode;
		private string _EpsProjName;
		private Guid? _FID;
		private string _Chapter;
		private string _ListingCode;
		private string _ListingName;
		private float? _ListingPrice;
		private float? _ListingNum;
		private float? _Amount;
		private float? _PlanNum;
		private float? _PlanPrice;
		private DateTime? _PlanSatrt;
		private DateTime? _PlanEnd;
		private string _S_ISBN;
		private float? _Ndljtz;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public Guid ID
		{
			get { return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Code")]
		public string Code
		{
			get { return _Code; }
			set
			{
				this.OnPropertyValueChange("Code");
				this._Code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Title")]
		public string Title
		{
			get { return _Title; }
			set
			{
				this.OnPropertyValueChange("Title");
				this._Title = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TableName")]
		public string TableName
		{
			get { return _TableName; }
			set
			{
				this.OnPropertyValueChange("TableName");
				this._TableName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BizAreaId")]
		public Guid? BizAreaId
		{
			get { return _BizAreaId; }
			set
			{
				this.OnPropertyValueChange("BizAreaId");
				this._BizAreaId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Sequ")]
		public int? Sequ
		{
			get { return _Sequ; }
			set
			{
				this.OnPropertyValueChange("Sequ");
				this._Sequ = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Status")]
		public int? Status
		{
			get { return _Status; }
			set
			{
				this.OnPropertyValueChange("Status");
				this._Status = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegHumId")]
		public Guid? RegHumId
		{
			get { return _RegHumId; }
			set
			{
				this.OnPropertyValueChange("RegHumId");
				this._RegHumId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegHumName")]
		public string RegHumName
		{
			get { return _RegHumName; }
			set
			{
				this.OnPropertyValueChange("RegHumName");
				this._RegHumName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegDate")]
		public DateTime? RegDate
		{
			get { return _RegDate; }
			set
			{
				this.OnPropertyValueChange("RegDate");
				this._RegDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegPosiId")]
		public Guid? RegPosiId
		{
			get { return _RegPosiId; }
			set
			{
				this.OnPropertyValueChange("RegPosiId");
				this._RegPosiId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegDeptId")]
		public Guid? RegDeptId
		{
			get { return _RegDeptId; }
			set
			{
				this.OnPropertyValueChange("RegDeptId");
				this._RegDeptId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("EpsProjId")]
		public Guid? EpsProjId
		{
			get { return _EpsProjId; }
			set
			{
				this.OnPropertyValueChange("EpsProjId");
				this._EpsProjId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RecycleHumId")]
		public Guid? RecycleHumId
		{
			get { return _RecycleHumId; }
			set
			{
				this.OnPropertyValueChange("RecycleHumId");
				this._RecycleHumId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UpdHumId")]
		public Guid? UpdHumId
		{
			get { return _UpdHumId; }
			set
			{
				this.OnPropertyValueChange("UpdHumId");
				this._UpdHumId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UpdHumName")]
		public string UpdHumName
		{
			get { return _UpdHumName; }
			set
			{
				this.OnPropertyValueChange("UpdHumName");
				this._UpdHumName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UpdDate")]
		public DateTime? UpdDate
		{
			get { return _UpdDate; }
			set
			{
				this.OnPropertyValueChange("UpdDate");
				this._UpdDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ApprHumId")]
		public Guid? ApprHumId
		{
			get { return _ApprHumId; }
			set
			{
				this.OnPropertyValueChange("ApprHumId");
				this._ApprHumId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ApprHumName")]
		public string ApprHumName
		{
			get { return _ApprHumName; }
			set
			{
				this.OnPropertyValueChange("ApprHumName");
				this._ApprHumName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ApprDate")]
		public DateTime? ApprDate
		{
			get { return _ApprDate; }
			set
			{
				this.OnPropertyValueChange("ApprDate");
				this._ApprDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get { return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OwnProjId")]
		public Guid? OwnProjId
		{
			get { return _OwnProjId; }
			set
			{
				this.OnPropertyValueChange("OwnProjId");
				this._OwnProjId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OwnProjName")]
		public string OwnProjName
		{
			get { return _OwnProjName; }
			set
			{
				this.OnPropertyValueChange("OwnProjName");
				this._OwnProjName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("EpsProjCode")]
		public string EpsProjCode
		{
			get { return _EpsProjCode; }
			set
			{
				this.OnPropertyValueChange("EpsProjCode");
				this._EpsProjCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("EpsProjName")]
		public string EpsProjName
		{
			get { return _EpsProjName; }
			set
			{
				this.OnPropertyValueChange("EpsProjName");
				this._EpsProjName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FID")]
		public Guid? FID
		{
			get { return _FID; }
			set
			{
				this.OnPropertyValueChange("FID");
				this._FID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Chapter")]
		public string Chapter
		{
			get { return _Chapter; }
			set
			{
				this.OnPropertyValueChange("Chapter");
				this._Chapter = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ListingCode")]
		public string ListingCode
		{
			get { return _ListingCode; }
			set
			{
				this.OnPropertyValueChange("ListingCode");
				this._ListingCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ListingName")]
		public string ListingName
		{
			get { return _ListingName; }
			set
			{
				this.OnPropertyValueChange("ListingName");
				this._ListingName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ListingPrice")]
		public float? ListingPrice
		{
			get { return _ListingPrice; }
			set
			{
				this.OnPropertyValueChange("ListingPrice");
				this._ListingPrice = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ListingNum")]
		public float? ListingNum
		{
			get { return _ListingNum; }
			set
			{
				this.OnPropertyValueChange("ListingNum");
				this._ListingNum = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Amount")]
		public float? Amount
		{
			get { return _Amount; }
			set
			{
				this.OnPropertyValueChange("Amount");
				this._Amount = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PlanNum")]
		public float? PlanNum
		{
			get { return _PlanNum; }
			set
			{
				this.OnPropertyValueChange("PlanNum");
				this._PlanNum = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PlanPrice")]
		public float? PlanPrice
		{
			get { return _PlanPrice; }
			set
			{
				this.OnPropertyValueChange("PlanPrice");
				this._PlanPrice = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PlanSatrt")]
		public DateTime? PlanSatrt
		{
			get { return _PlanSatrt; }
			set
			{
				this.OnPropertyValueChange("PlanSatrt");
				this._PlanSatrt = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PlanEnd")]
		public DateTime? PlanEnd
		{
			get { return _PlanEnd; }
			set
			{
				this.OnPropertyValueChange("PlanEnd");
				this._PlanEnd = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("S_ISBN")]
		public string S_ISBN
		{
			get { return _S_ISBN; }
			set
			{
				this.OnPropertyValueChange("S_ISBN");
				this._S_ISBN = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Ndljtz")]
		public float? Ndljtz
		{
			get { return _Ndljtz; }
			set
			{
				this.OnPropertyValueChange("Ndljtz");
				this._Ndljtz = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Code,
				_.Title,
				_.TableName,
				_.BizAreaId,
				_.Sequ,
				_.Status,
				_.RegHumId,
				_.RegHumName,
				_.RegDate,
				_.RegPosiId,
				_.RegDeptId,
				_.EpsProjId,
				_.RecycleHumId,
				_.UpdHumId,
				_.UpdHumName,
				_.UpdDate,
				_.ApprHumId,
				_.ApprHumName,
				_.ApprDate,
				_.Remark,
				_.OwnProjId,
				_.OwnProjName,
				_.EpsProjCode,
				_.EpsProjName,
				_.FID,
				_.Chapter,
				_.ListingCode,
				_.ListingName,
				_.ListingPrice,
				_.ListingNum,
				_.Amount,
				_.PlanNum,
				_.PlanPrice,
				_.PlanSatrt,
				_.PlanEnd,
				_.S_ISBN,
				_.Ndljtz,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Code,
				this._Title,
				this._TableName,
				this._BizAreaId,
				this._Sequ,
				this._Status,
				this._RegHumId,
				this._RegHumName,
				this._RegDate,
				this._RegPosiId,
				this._RegDeptId,
				this._EpsProjId,
				this._RecycleHumId,
				this._UpdHumId,
				this._UpdHumName,
				this._UpdDate,
				this._ApprHumId,
				this._ApprHumName,
				this._ApprDate,
				this._Remark,
				this._OwnProjId,
				this._OwnProjName,
				this._EpsProjCode,
				this._EpsProjName,
				this._FID,
				this._Chapter,
				this._ListingCode,
				this._ListingName,
				this._ListingPrice,
				this._ListingNum,
				this._Amount,
				this._PlanNum,
				this._PlanPrice,
				this._PlanSatrt,
				this._PlanEnd,
				this._S_ISBN,
				this._Ndljtz,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "NPS_BOQ");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Code = new Field("Code", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TableName = new Field("TableName", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BizAreaId = new Field("BizAreaId", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sequ = new Field("Sequ", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Status = new Field("Status", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RegHumId = new Field("RegHumId", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RegHumName = new Field("RegHumName", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RegDate = new Field("RegDate", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RegPosiId = new Field("RegPosiId", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RegDeptId = new Field("RegDeptId", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EpsProjId = new Field("EpsProjId", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RecycleHumId = new Field("RecycleHumId", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdHumId = new Field("UpdHumId", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdHumName = new Field("UpdHumName", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdDate = new Field("UpdDate", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ApprHumId = new Field("ApprHumId", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ApprHumName = new Field("ApprHumName", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ApprDate = new Field("ApprDate", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OwnProjId = new Field("OwnProjId", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OwnProjName = new Field("OwnProjName", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EpsProjCode = new Field("EpsProjCode", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EpsProjName = new Field("EpsProjName", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FID = new Field("FID", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Chapter = new Field("Chapter", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ListingCode = new Field("ListingCode", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ListingName = new Field("ListingName", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ListingPrice = new Field("ListingPrice", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ListingNum = new Field("ListingNum", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Amount = new Field("Amount", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PlanNum = new Field("PlanNum", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PlanPrice = new Field("PlanPrice", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PlanSatrt = new Field("PlanSatrt", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PlanEnd = new Field("PlanEnd", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field S_ISBN = new Field("S_ISBN", "NPS_BOQ", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Ndljtz = new Field("Ndljtz", "NPS_BOQ", "");
		}
		#endregion
	}
}