//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace JJWBSService
{
	/// <summary>
	/// 实体类PLN_taskproc。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("PLN_taskproc")]
	[Serializable]
	[DataContract]
	public partial class PLN_taskproc : Entity
	{
		#region Model
		private int _proc_id;
		private int _proj_id;
		private int _wbs_id;
		private int _task_id;
		private string _task_guid;
		private int? _seq_num;
		private bool? _CompleteOrNot;
		private string _proc_name;
		private string _proc_descri;
		private int? _est_wt;
		private decimal? _complete_pct;
		private DateTime? _act_end_date;
		private bool? _SysOrNot;
		private int? _target_end_date_lag;
		private int? _expect_end_date_lag;
		private int? _rsrc_id;
		private int? _temp_id;
		private DateTime? _update_date;
		private int? _p3ec_proc_id;
		private int? _p3ec_flag;
		private string _proc_guid;
		private string _proj_guid;
		private string _plan_guid;
		private int? _plan_id;
		private string _wbs_guid;
		private string _rsrc_guid;
		private string _temp_guid;
		private float? _est_wt_pct;
		private string _keyword;
		private string _formid;
		private string _update_user;
		private DateTime? _create_date;
		private string _create_user;
		private int? _delete_session_id;
		private DateTime? _delete_date;
		private DateTime? _target_end_date;
		private string _proc_code;
		private DateTime? _PLN_target_start_date;
		private DateTime? _PLN_target_end_date;
		private DateTime? _PLN_act_end_date;
		private DateTime? _PLN_act_start_date;

		/// <summary>
		/// 
		/// </summary>
		[Field("proc_id")]
		[DataMember]
		public int proc_id
		{
			get { return _proc_id; }
			set
			{
				this.OnPropertyValueChange("proc_id");
				this._proc_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proj_id")]
		[DataMember]
		public int proj_id
		{
			get { return _proj_id; }
			set
			{
				this.OnPropertyValueChange("proj_id");
				this._proj_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("wbs_id")]
		[DataMember]
		public int wbs_id
		{
			get { return _wbs_id; }
			set
			{
				this.OnPropertyValueChange("wbs_id");
				this._wbs_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("task_id")]
		[DataMember]
		public int task_id
		{
			get { return _task_id; }
			set
			{
				this.OnPropertyValueChange("task_id");
				this._task_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("task_guid")]
		[DataMember]
		public string task_guid
		{
			get { return _task_guid; }
			set
			{
				this.OnPropertyValueChange("task_guid");
				this._task_guid = value;
			}
		}
		/// <summary>
		/// 排序号
		/// </summary>
		[Field("seq_num")]
		[DataMember]
		public int? seq_num
		{
			get { return _seq_num; }
			set
			{
				this.OnPropertyValueChange("seq_num");
				this._seq_num = value;
			}
		}
		/// <summary>
		/// 是否完成1是，0否
		/// </summary>
		[Field("CompleteOrNot")]
		[DataMember]
		public bool? CompleteOrNot
		{
			get { return _CompleteOrNot; }
			set
			{
				this.OnPropertyValueChange("CompleteOrNot");
				this._CompleteOrNot = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proc_name")]
		[DataMember]
		public string proc_name
		{
			get { return _proc_name; }
			set
			{
				this.OnPropertyValueChange("proc_name");
				this._proc_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proc_descri")]
		[DataMember]
		public string proc_descri
		{
			get { return _proc_descri; }
			set
			{
				this.OnPropertyValueChange("proc_descri");
				this._proc_descri = value;
			}
		}
		/// <summary>
		/// 权重
		/// </summary>
		[Field("est_wt")]
		[DataMember]
		public int? est_wt
		{
			get { return _est_wt; }
			set
			{
				this.OnPropertyValueChange("est_wt");
				this._est_wt = value;
			}
		}
		/// <summary>
		/// 完成百分比
		/// </summary>
		[Field("complete_pct")]
		[DataMember]
		public decimal? complete_pct
		{
			get { return _complete_pct; }
			set
			{
				this.OnPropertyValueChange("complete_pct");
				this._complete_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_end_date")]
		[DataMember]
		public DateTime? act_end_date
		{
			get { return _act_end_date; }
			set
			{
				this.OnPropertyValueChange("act_end_date");
				this._act_end_date = value;
			}
		}
		/// <summary>
		/// 是否是系统生成,不能改变结构的,1是,0否
		/// </summary>
		[Field("SysOrNot")]
		[DataMember]
		public bool? SysOrNot
		{
			get { return _SysOrNot; }
			set
			{
				this.OnPropertyValueChange("SysOrNot");
				this._SysOrNot = value;
			}
		}
		/// <summary>
		/// 计划执行间隔
		/// </summary>
		[Field("target_end_date_lag")]
		[DataMember]
		public int? target_end_date_lag
		{
			get { return _target_end_date_lag; }
			set
			{
				this.OnPropertyValueChange("target_end_date_lag");
				this._target_end_date_lag = value;
			}
		}
		/// <summary>
		/// 期望执行间隔
		/// </summary>
		[Field("expect_end_date_lag")]
		[DataMember]
		public int? expect_end_date_lag
		{
			get { return _expect_end_date_lag; }
			set
			{
				this.OnPropertyValueChange("expect_end_date_lag");
				this._expect_end_date_lag = value;
			}
		}
		/// <summary>
		/// 责任人id
		/// </summary>
		[Field("rsrc_id")]
		[DataMember]
		public int? rsrc_id
		{
			get { return _rsrc_id; }
			set
			{
				this.OnPropertyValueChange("rsrc_id");
				this._rsrc_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("temp_id")]
		[DataMember]
		public int? temp_id
		{
			get { return _temp_id; }
			set
			{
				this.OnPropertyValueChange("temp_id");
				this._temp_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("update_date")]
		[DataMember]
		public DateTime? update_date
		{
			get { return _update_date; }
			set
			{
				this.OnPropertyValueChange("update_date");
				this._update_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("p3ec_proc_id")]
		[DataMember]
		public int? p3ec_proc_id
		{
			get { return _p3ec_proc_id; }
			set
			{
				this.OnPropertyValueChange("p3ec_proc_id");
				this._p3ec_proc_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("p3ec_flag")]
		[DataMember]
		public int? p3ec_flag
		{
			get { return _p3ec_flag; }
			set
			{
				this.OnPropertyValueChange("p3ec_flag");
				this._p3ec_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proc_guid")]
		[DataMember]
		public string proc_guid
		{
			get { return _proc_guid; }
			set
			{
				this.OnPropertyValueChange("proc_guid");
				this._proc_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proj_guid")]
		[DataMember]
		public string proj_guid
		{
			get { return _proj_guid; }
			set
			{
				this.OnPropertyValueChange("proj_guid");
				this._proj_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_guid")]
		[DataMember]
		public string plan_guid
		{
			get { return _plan_guid; }
			set
			{
				this.OnPropertyValueChange("plan_guid");
				this._plan_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_id")]
		[DataMember]
		public int? plan_id
		{
			get { return _plan_id; }
			set
			{
				this.OnPropertyValueChange("plan_id");
				this._plan_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("wbs_guid")]
		[DataMember]
		public string wbs_guid
		{
			get { return _wbs_guid; }
			set
			{
				this.OnPropertyValueChange("wbs_guid");
				this._wbs_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("rsrc_guid")]
		[DataMember]
		public string rsrc_guid
		{
			get { return _rsrc_guid; }
			set
			{
				this.OnPropertyValueChange("rsrc_guid");
				this._rsrc_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("temp_guid")]
		[DataMember]
		public string temp_guid
		{
			get { return _temp_guid; }
			set
			{
				this.OnPropertyValueChange("temp_guid");
				this._temp_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("est_wt_pct")]
		[DataMember]
		public float? est_wt_pct
		{
			get { return _est_wt_pct; }
			set
			{
				this.OnPropertyValueChange("est_wt_pct");
				this._est_wt_pct = value;
			}
		}
		/// <summary>
		/// 关联业务表单
		/// </summary>
		[Field("keyword")]
		[DataMember]
		public string keyword
		{
			get { return _keyword; }
			set
			{
				this.OnPropertyValueChange("keyword");
				this._keyword = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("formid")]
		[DataMember]
		public string formid
		{
			get { return _formid; }
			set
			{
				this.OnPropertyValueChange("formid");
				this._formid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("update_user")]
		[DataMember]
		public string update_user
		{
			get { return _update_user; }
			set
			{
				this.OnPropertyValueChange("update_user");
				this._update_user = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("create_date")]
		[DataMember]
		public DateTime? create_date
		{
			get { return _create_date; }
			set
			{
				this.OnPropertyValueChange("create_date");
				this._create_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("create_user")]
		[DataMember]
		public string create_user
		{
			get { return _create_user; }
			set
			{
				this.OnPropertyValueChange("create_user");
				this._create_user = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("delete_session_id")]
		[DataMember]
		public int? delete_session_id
		{
			get { return _delete_session_id; }
			set
			{
				this.OnPropertyValueChange("delete_session_id");
				this._delete_session_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("delete_date")]
		[DataMember]
		public DateTime? delete_date
		{
			get { return _delete_date; }
			set
			{
				this.OnPropertyValueChange("delete_date");
				this._delete_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_end_date")]
		[DataMember]
		public DateTime? target_end_date
		{
			get { return _target_end_date; }
			set
			{
				this.OnPropertyValueChange("target_end_date");
				this._target_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proc_code")]
		[DataMember]
		public string proc_code
		{
			get { return _proc_code; }
			set
			{
				this.OnPropertyValueChange("proc_code");
				this._proc_code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PLN_target_start_date")]
		[DataMember]
		public DateTime? PLN_target_start_date
		{
			get { return _PLN_target_start_date; }
			set
			{
				this.OnPropertyValueChange("PLN_target_start_date");
				this._PLN_target_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PLN_target_end_date")]
		[DataMember]
		public DateTime? PLN_target_end_date
		{
			get { return _PLN_target_end_date; }
			set
			{
				this.OnPropertyValueChange("PLN_target_end_date");
				this._PLN_target_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PLN_act_end_date")]
		[DataMember]
		public DateTime? PLN_act_end_date
		{
			get { return _PLN_act_end_date; }
			set
			{
				this.OnPropertyValueChange("PLN_act_end_date");
				this._PLN_act_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PLN_act_start_date")]
		[DataMember]
		public DateTime? PLN_act_start_date
		{
			get { return _PLN_act_start_date; }
			set
			{
				this.OnPropertyValueChange("PLN_act_start_date");
				this._PLN_act_start_date = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.proc_id,
				_.proc_guid,
			};
		}
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.proc_id;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.proc_id,
				_.proj_id,
				_.wbs_id,
				_.task_id,
				_.task_guid,
				_.seq_num,
				_.CompleteOrNot,
				_.proc_name,
				_.proc_descri,
				_.est_wt,
				_.complete_pct,
				_.act_end_date,
				_.SysOrNot,
				_.target_end_date_lag,
				_.expect_end_date_lag,
				_.rsrc_id,
				_.temp_id,
				_.update_date,
				_.p3ec_proc_id,
				_.p3ec_flag,
				_.proc_guid,
				_.proj_guid,
				_.plan_guid,
				_.plan_id,
				_.wbs_guid,
				_.rsrc_guid,
				_.temp_guid,
				_.est_wt_pct,
				_.keyword,
				_.formid,
				_.update_user,
				_.create_date,
				_.create_user,
				_.delete_session_id,
				_.delete_date,
				_.target_end_date,
				_.proc_code,
				_.PLN_target_start_date,
				_.PLN_target_end_date,
				_.PLN_act_end_date,
				_.PLN_act_start_date,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._proc_id,
				this._proj_id,
				this._wbs_id,
				this._task_id,
				this._task_guid,
				this._seq_num,
				this._CompleteOrNot,
				this._proc_name,
				this._proc_descri,
				this._est_wt,
				this._complete_pct,
				this._act_end_date,
				this._SysOrNot,
				this._target_end_date_lag,
				this._expect_end_date_lag,
				this._rsrc_id,
				this._temp_id,
				this._update_date,
				this._p3ec_proc_id,
				this._p3ec_flag,
				this._proc_guid,
				this._proj_guid,
				this._plan_guid,
				this._plan_id,
				this._wbs_guid,
				this._rsrc_guid,
				this._temp_guid,
				this._est_wt_pct,
				this._keyword,
				this._formid,
				this._update_user,
				this._create_date,
				this._create_user,
				this._delete_session_id,
				this._delete_date,
				this._target_end_date,
				this._proc_code,
				this._PLN_target_start_date,
				this._PLN_target_end_date,
				this._PLN_act_end_date,
				this._PLN_act_start_date,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "PLN_taskproc");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proc_id = new Field("proc_id", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proj_id = new Field("proj_id", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wbs_id = new Field("wbs_id", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field task_id = new Field("task_id", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field task_guid = new Field("task_guid", "PLN_taskproc", "");
			/// <summary>
			/// 排序号
			/// </summary>
			public readonly static Field seq_num = new Field("seq_num", "PLN_taskproc", "排序号");
			/// <summary>
			/// 是否完成1是，0否
			/// </summary>
			public readonly static Field CompleteOrNot = new Field("CompleteOrNot", "PLN_taskproc", "是否完成1是，0否");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proc_name = new Field("proc_name", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proc_descri = new Field("proc_descri", "PLN_taskproc", "");
			/// <summary>
			/// 权重
			/// </summary>
			public readonly static Field est_wt = new Field("est_wt", "PLN_taskproc", "权重");
			/// <summary>
			/// 完成百分比
			/// </summary>
			public readonly static Field complete_pct = new Field("complete_pct", "PLN_taskproc", "完成百分比");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_end_date = new Field("act_end_date", "PLN_taskproc", "");
			/// <summary>
			/// 是否是系统生成,不能改变结构的,1是,0否
			/// </summary>
			public readonly static Field SysOrNot = new Field("SysOrNot", "PLN_taskproc", "是否是系统生成,不能改变结构的,1是,0否");
			/// <summary>
			/// 计划执行间隔
			/// </summary>
			public readonly static Field target_end_date_lag = new Field("target_end_date_lag", "PLN_taskproc", "计划执行间隔");
			/// <summary>
			/// 期望执行间隔
			/// </summary>
			public readonly static Field expect_end_date_lag = new Field("expect_end_date_lag", "PLN_taskproc", "期望执行间隔");
			/// <summary>
			/// 责任人id
			/// </summary>
			public readonly static Field rsrc_id = new Field("rsrc_id", "PLN_taskproc", "责任人id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field temp_id = new Field("temp_id", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field update_date = new Field("update_date", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field p3ec_proc_id = new Field("p3ec_proc_id", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field p3ec_flag = new Field("p3ec_flag", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proc_guid = new Field("proc_guid", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proj_guid = new Field("proj_guid", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_guid = new Field("plan_guid", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_id = new Field("plan_id", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wbs_guid = new Field("wbs_guid", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field rsrc_guid = new Field("rsrc_guid", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field temp_guid = new Field("temp_guid", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field est_wt_pct = new Field("est_wt_pct", "PLN_taskproc", "");
			/// <summary>
			/// 关联业务表单
			/// </summary>
			public readonly static Field keyword = new Field("keyword", "PLN_taskproc", "关联业务表单");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field formid = new Field("formid", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field update_user = new Field("update_user", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field create_date = new Field("create_date", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field create_user = new Field("create_user", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field delete_session_id = new Field("delete_session_id", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field delete_date = new Field("delete_date", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_end_date = new Field("target_end_date", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proc_code = new Field("proc_code", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PLN_target_start_date = new Field("PLN_target_start_date", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PLN_target_end_date = new Field("PLN_target_end_date", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PLN_act_end_date = new Field("PLN_act_end_date", "PLN_taskproc", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PLN_act_start_date = new Field("PLN_act_start_date", "PLN_taskproc", "");
		}
		#endregion
	}
}