//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace JJWBSService.Modes
{
	/// <summary>
	/// 实体类PLN_TempPROJWBS。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("PLN_TempPROJWBS")]
	[Serializable]
	public partial class PLN_TempPROJWBS : Entity
	{
		#region Model
		private int _wbs_id;
		private string _wbs_guid;
		private int? _proj_id;
		private string _proj_guid;
		private int _obs_id;
		private string _obs_guid;
		private int _seq_num;
		private decimal? _est_wt;
		private decimal? _complete_pct;
		private string _proj_node_flag;
		private string _sum_data_flag;
		private string _status_code;
		private string _wbs_short_name;
		private string _wbs_name;
		private int? _phase_id;
		private int? _parent_wbs_id;
		private string _parent_wbs_guid;
		private int? _ev_user_pct;
		private decimal? _ev_etc_user_value;
		private decimal? _orig_cost;
		private decimal? _user_cost1;
		private decimal? _indep_remain_total_cost;
		private decimal? _ann_dscnt_rate_pct;
		private string _dscnt_period_type;
		private decimal? _indep_remain_work_qty;
		private DateTime? _anticip_start_date;
		private DateTime? _anticip_end_date;
		private string _ev_compute_type;
		private string _ev_etc_compute_type;
		private string _guid;
		private string _tmpl_guid;
		private int? _p3ec_wbs_id;
		private int? _p3ec_parentwbs_id;
		private int? _p3ec_flag;
		private int? _treelevel;
		private int? _haschild;
		private int? _discolor;
		private DateTime? _target_start_date;
		private DateTime? _target_end_date;
		private DateTime? _expect_start_date;
		private DateTime? _expect_end_date;
		private DateTime? _act_start_date;
		private DateTime? _act_end_date;
		private bool? _SysOrNot;
		private bool? _allowModifyTaskOrNot;
		private string _complete_pct_type;
		private decimal? _target_drtn_hr_cnt;
		private decimal? _remain_drtn_hr_cnt;
		private DateTime? _update_date;
		private DateTime? _start_date;
		private DateTime? _end_date;
		private string _LongCode;
		private int? _plan_id;
		private string _plan_guid;
		private decimal? _est_wt_pct;
		private DateTime? _require_start_date;
		private DateTime? _require_end_date;
		private string _main_wbs_guid;
		private decimal? _bcws_cost;
		private decimal? _bcwp_cost;
		private decimal? _acwp_cost;
		private float? _budget_cost;
		private Guid? _reghumanid;
		private string _reghumanname;
		private Guid? _rsrc_guid;
		private string _rsrc_name;
		private Guid? _responsibleid;
		private string _responsiblename;
		private string _update_user;
		private DateTime? _create_date;
		private string _create_user;
		private int? _delete_session_id;
		private DateTime? _delete_date;
		private decimal? _target_complete_pct;
		private decimal? _period_target_complete_pct;
		private DateTime? _restart_date;
		private DateTime? _reend_date;
		private decimal? _plan_pct;
		private string _wbs_guid_before;
		private string _dept_name;
		private string _dept_guid;
		private string _remark;
		private decimal? _plan_hour;
		private decimal? _act_hour;

		/// <summary>
		/// 
		/// </summary>
		[Field("wbs_id")]
		public int wbs_id
		{
			get { return _wbs_id; }
			set
			{
				this.OnPropertyValueChange("wbs_id");
				this._wbs_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("wbs_guid")]
		public string wbs_guid
		{
			get { return _wbs_guid; }
			set
			{
				this.OnPropertyValueChange("wbs_guid");
				this._wbs_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proj_id")]
		public int? proj_id
		{
			get { return _proj_id; }
			set
			{
				this.OnPropertyValueChange("proj_id");
				this._proj_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proj_guid")]
		public string proj_guid
		{
			get { return _proj_guid; }
			set
			{
				this.OnPropertyValueChange("proj_guid");
				this._proj_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("obs_id")]
		public int obs_id
		{
			get { return _obs_id; }
			set
			{
				this.OnPropertyValueChange("obs_id");
				this._obs_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("obs_guid")]
		public string obs_guid
		{
			get { return _obs_guid; }
			set
			{
				this.OnPropertyValueChange("obs_guid");
				this._obs_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("seq_num")]
		public int seq_num
		{
			get { return _seq_num; }
			set
			{
				this.OnPropertyValueChange("seq_num");
				this._seq_num = value;
			}
		}
		/// <summary>
		/// 权重
		/// </summary>
		[Field("est_wt")]
		public decimal? est_wt
		{
			get { return _est_wt; }
			set
			{
				this.OnPropertyValueChange("est_wt");
				this._est_wt = value;
			}
		}
		/// <summary>
		/// 完成百分比
		/// </summary>
		[Field("complete_pct")]
		public decimal? complete_pct
		{
			get { return _complete_pct; }
			set
			{
				this.OnPropertyValueChange("complete_pct");
				this._complete_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proj_node_flag")]
		public string proj_node_flag
		{
			get { return _proj_node_flag; }
			set
			{
				this.OnPropertyValueChange("proj_node_flag");
				this._proj_node_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("sum_data_flag")]
		public string sum_data_flag
		{
			get { return _sum_data_flag; }
			set
			{
				this.OnPropertyValueChange("sum_data_flag");
				this._sum_data_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("status_code")]
		public string status_code
		{
			get { return _status_code; }
			set
			{
				this.OnPropertyValueChange("status_code");
				this._status_code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("wbs_short_name")]
		public string wbs_short_name
		{
			get { return _wbs_short_name; }
			set
			{
				this.OnPropertyValueChange("wbs_short_name");
				this._wbs_short_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("wbs_name")]
		public string wbs_name
		{
			get { return _wbs_name; }
			set
			{
				this.OnPropertyValueChange("wbs_name");
				this._wbs_name = value;
			}
		}
		/// <summary>
		/// 尚不知用途
		/// </summary>
		[Field("phase_id")]
		public int? phase_id
		{
			get { return _phase_id; }
			set
			{
				this.OnPropertyValueChange("phase_id");
				this._phase_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("parent_wbs_id")]
		public int? parent_wbs_id
		{
			get { return _parent_wbs_id; }
			set
			{
				this.OnPropertyValueChange("parent_wbs_id");
				this._parent_wbs_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("parent_wbs_guid")]
		public string parent_wbs_guid
		{
			get { return _parent_wbs_guid; }
			set
			{
				this.OnPropertyValueChange("parent_wbs_guid");
				this._parent_wbs_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ev_user_pct")]
		public int? ev_user_pct
		{
			get { return _ev_user_pct; }
			set
			{
				this.OnPropertyValueChange("ev_user_pct");
				this._ev_user_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ev_etc_user_value")]
		public decimal? ev_etc_user_value
		{
			get { return _ev_etc_user_value; }
			set
			{
				this.OnPropertyValueChange("ev_etc_user_value");
				this._ev_etc_user_value = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("orig_cost")]
		public decimal? orig_cost
		{
			get { return _orig_cost; }
			set
			{
				this.OnPropertyValueChange("orig_cost");
				this._orig_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("user_cost1")]
		public decimal? user_cost1
		{
			get { return _user_cost1; }
			set
			{
				this.OnPropertyValueChange("user_cost1");
				this._user_cost1 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("indep_remain_total_cost")]
		public decimal? indep_remain_total_cost
		{
			get { return _indep_remain_total_cost; }
			set
			{
				this.OnPropertyValueChange("indep_remain_total_cost");
				this._indep_remain_total_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ann_dscnt_rate_pct")]
		public decimal? ann_dscnt_rate_pct
		{
			get { return _ann_dscnt_rate_pct; }
			set
			{
				this.OnPropertyValueChange("ann_dscnt_rate_pct");
				this._ann_dscnt_rate_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("dscnt_period_type")]
		public string dscnt_period_type
		{
			get { return _dscnt_period_type; }
			set
			{
				this.OnPropertyValueChange("dscnt_period_type");
				this._dscnt_period_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("indep_remain_work_qty")]
		public decimal? indep_remain_work_qty
		{
			get { return _indep_remain_work_qty; }
			set
			{
				this.OnPropertyValueChange("indep_remain_work_qty");
				this._indep_remain_work_qty = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("anticip_start_date")]
		public DateTime? anticip_start_date
		{
			get { return _anticip_start_date; }
			set
			{
				this.OnPropertyValueChange("anticip_start_date");
				this._anticip_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("anticip_end_date")]
		public DateTime? anticip_end_date
		{
			get { return _anticip_end_date; }
			set
			{
				this.OnPropertyValueChange("anticip_end_date");
				this._anticip_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ev_compute_type")]
		public string ev_compute_type
		{
			get { return _ev_compute_type; }
			set
			{
				this.OnPropertyValueChange("ev_compute_type");
				this._ev_compute_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ev_etc_compute_type")]
		public string ev_etc_compute_type
		{
			get { return _ev_etc_compute_type; }
			set
			{
				this.OnPropertyValueChange("ev_etc_compute_type");
				this._ev_etc_compute_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("guid")]
		public string guid
		{
			get { return _guid; }
			set
			{
				this.OnPropertyValueChange("guid");
				this._guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("tmpl_guid")]
		public string tmpl_guid
		{
			get { return _tmpl_guid; }
			set
			{
				this.OnPropertyValueChange("tmpl_guid");
				this._tmpl_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("p3ec_wbs_id")]
		public int? p3ec_wbs_id
		{
			get { return _p3ec_wbs_id; }
			set
			{
				this.OnPropertyValueChange("p3ec_wbs_id");
				this._p3ec_wbs_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("p3ec_parentwbs_id")]
		public int? p3ec_parentwbs_id
		{
			get { return _p3ec_parentwbs_id; }
			set
			{
				this.OnPropertyValueChange("p3ec_parentwbs_id");
				this._p3ec_parentwbs_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("p3ec_flag")]
		public int? p3ec_flag
		{
			get { return _p3ec_flag; }
			set
			{
				this.OnPropertyValueChange("p3ec_flag");
				this._p3ec_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("treelevel")]
		public int? treelevel
		{
			get { return _treelevel; }
			set
			{
				this.OnPropertyValueChange("treelevel");
				this._treelevel = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("haschild")]
		public int? haschild
		{
			get { return _haschild; }
			set
			{
				this.OnPropertyValueChange("haschild");
				this._haschild = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("discolor")]
		public int? discolor
		{
			get { return _discolor; }
			set
			{
				this.OnPropertyValueChange("discolor");
				this._discolor = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_start_date")]
		public DateTime? target_start_date
		{
			get { return _target_start_date; }
			set
			{
				this.OnPropertyValueChange("target_start_date");
				this._target_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_end_date")]
		public DateTime? target_end_date
		{
			get { return _target_end_date; }
			set
			{
				this.OnPropertyValueChange("target_end_date");
				this._target_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("expect_start_date")]
		public DateTime? expect_start_date
		{
			get { return _expect_start_date; }
			set
			{
				this.OnPropertyValueChange("expect_start_date");
				this._expect_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("expect_end_date")]
		public DateTime? expect_end_date
		{
			get { return _expect_end_date; }
			set
			{
				this.OnPropertyValueChange("expect_end_date");
				this._expect_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_start_date")]
		public DateTime? act_start_date
		{
			get { return _act_start_date; }
			set
			{
				this.OnPropertyValueChange("act_start_date");
				this._act_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_end_date")]
		public DateTime? act_end_date
		{
			get { return _act_end_date; }
			set
			{
				this.OnPropertyValueChange("act_end_date");
				this._act_end_date = value;
			}
		}
		/// <summary>
		/// 是否是系统生成,不能改变结构的,1是,0否
		/// </summary>
		[Field("SysOrNot")]
		public bool? SysOrNot
		{
			get { return _SysOrNot; }
			set
			{
				this.OnPropertyValueChange("SysOrNot");
				this._SysOrNot = value;
			}
		}
		/// <summary>
		/// 是否允许增、删task，1允许，0不允许
		/// </summary>
		[Field("allowModifyTaskOrNot")]
		public bool? allowModifyTaskOrNot
		{
			get { return _allowModifyTaskOrNot; }
			set
			{
				this.OnPropertyValueChange("allowModifyTaskOrNot");
				this._allowModifyTaskOrNot = value;
			}
		}
		/// <summary>
		/// 进度计算的方式 1、基于task；2、基于填报；3、基于里程碑点
		/// </summary>
		[Field("complete_pct_type")]
		public string complete_pct_type
		{
			get { return _complete_pct_type; }
			set
			{
				this.OnPropertyValueChange("complete_pct_type");
				this._complete_pct_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_drtn_hr_cnt")]
		public decimal? target_drtn_hr_cnt
		{
			get { return _target_drtn_hr_cnt; }
			set
			{
				this.OnPropertyValueChange("target_drtn_hr_cnt");
				this._target_drtn_hr_cnt = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("remain_drtn_hr_cnt")]
		public decimal? remain_drtn_hr_cnt
		{
			get { return _remain_drtn_hr_cnt; }
			set
			{
				this.OnPropertyValueChange("remain_drtn_hr_cnt");
				this._remain_drtn_hr_cnt = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("update_date")]
		public DateTime? update_date
		{
			get { return _update_date; }
			set
			{
				this.OnPropertyValueChange("update_date");
				this._update_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("start_date")]
		public DateTime? start_date
		{
			get { return _start_date; }
			set
			{
				this.OnPropertyValueChange("start_date");
				this._start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("end_date")]
		public DateTime? end_date
		{
			get { return _end_date; }
			set
			{
				this.OnPropertyValueChange("end_date");
				this._end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LongCode")]
		public string LongCode
		{
			get { return _LongCode; }
			set
			{
				this.OnPropertyValueChange("LongCode");
				this._LongCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_id")]
		public int? plan_id
		{
			get { return _plan_id; }
			set
			{
				this.OnPropertyValueChange("plan_id");
				this._plan_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_guid")]
		public string plan_guid
		{
			get { return _plan_guid; }
			set
			{
				this.OnPropertyValueChange("plan_guid");
				this._plan_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("est_wt_pct")]
		public decimal? est_wt_pct
		{
			get { return _est_wt_pct; }
			set
			{
				this.OnPropertyValueChange("est_wt_pct");
				this._est_wt_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("require_start_date")]
		public DateTime? require_start_date
		{
			get { return _require_start_date; }
			set
			{
				this.OnPropertyValueChange("require_start_date");
				this._require_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("require_end_date")]
		public DateTime? require_end_date
		{
			get { return _require_end_date; }
			set
			{
				this.OnPropertyValueChange("require_end_date");
				this._require_end_date = value;
			}
		}
		/// <summary>
		/// 发包后主计划的WBS 主键
		/// </summary>
		[Field("main_wbs_guid")]
		public string main_wbs_guid
		{
			get { return _main_wbs_guid; }
			set
			{
				this.OnPropertyValueChange("main_wbs_guid");
				this._main_wbs_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("bcws_cost")]
		public decimal? bcws_cost
		{
			get { return _bcws_cost; }
			set
			{
				this.OnPropertyValueChange("bcws_cost");
				this._bcws_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("bcwp_cost")]
		public decimal? bcwp_cost
		{
			get { return _bcwp_cost; }
			set
			{
				this.OnPropertyValueChange("bcwp_cost");
				this._bcwp_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("acwp_cost")]
		public decimal? acwp_cost
		{
			get { return _acwp_cost; }
			set
			{
				this.OnPropertyValueChange("acwp_cost");
				this._acwp_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("budget_cost")]
		public float? budget_cost
		{
			get { return _budget_cost; }
			set
			{
				this.OnPropertyValueChange("budget_cost");
				this._budget_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("reghumanid")]
		public Guid? reghumanid
		{
			get { return _reghumanid; }
			set
			{
				this.OnPropertyValueChange("reghumanid");
				this._reghumanid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("reghumanname")]
		public string reghumanname
		{
			get { return _reghumanname; }
			set
			{
				this.OnPropertyValueChange("reghumanname");
				this._reghumanname = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("rsrc_guid")]
		public Guid? rsrc_guid
		{
			get { return _rsrc_guid; }
			set
			{
				this.OnPropertyValueChange("rsrc_guid");
				this._rsrc_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("rsrc_name")]
		public string rsrc_name
		{
			get { return _rsrc_name; }
			set
			{
				this.OnPropertyValueChange("rsrc_name");
				this._rsrc_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("responsibleid")]
		public Guid? responsibleid
		{
			get { return _responsibleid; }
			set
			{
				this.OnPropertyValueChange("responsibleid");
				this._responsibleid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("responsiblename")]
		public string responsiblename
		{
			get { return _responsiblename; }
			set
			{
				this.OnPropertyValueChange("responsiblename");
				this._responsiblename = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("update_user")]
		public string update_user
		{
			get { return _update_user; }
			set
			{
				this.OnPropertyValueChange("update_user");
				this._update_user = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("create_date")]
		public DateTime? create_date
		{
			get { return _create_date; }
			set
			{
				this.OnPropertyValueChange("create_date");
				this._create_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("create_user")]
		public string create_user
		{
			get { return _create_user; }
			set
			{
				this.OnPropertyValueChange("create_user");
				this._create_user = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("delete_session_id")]
		public int? delete_session_id
		{
			get { return _delete_session_id; }
			set
			{
				this.OnPropertyValueChange("delete_session_id");
				this._delete_session_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("delete_date")]
		public DateTime? delete_date
		{
			get { return _delete_date; }
			set
			{
				this.OnPropertyValueChange("delete_date");
				this._delete_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_complete_pct")]
		public decimal? target_complete_pct
		{
			get { return _target_complete_pct; }
			set
			{
				this.OnPropertyValueChange("target_complete_pct");
				this._target_complete_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("period_target_complete_pct")]
		public decimal? period_target_complete_pct
		{
			get { return _period_target_complete_pct; }
			set
			{
				this.OnPropertyValueChange("period_target_complete_pct");
				this._period_target_complete_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("restart_date")]
		public DateTime? restart_date
		{
			get { return _restart_date; }
			set
			{
				this.OnPropertyValueChange("restart_date");
				this._restart_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("reend_date")]
		public DateTime? reend_date
		{
			get { return _reend_date; }
			set
			{
				this.OnPropertyValueChange("reend_date");
				this._reend_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_pct")]
		public decimal? plan_pct
		{
			get { return _plan_pct; }
			set
			{
				this.OnPropertyValueChange("plan_pct");
				this._plan_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("wbs_guid_before")]
		public string wbs_guid_before
		{
			get { return _wbs_guid_before; }
			set
			{
				this.OnPropertyValueChange("wbs_guid_before");
				this._wbs_guid_before = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("dept_name")]
		public string dept_name
		{
			get { return _dept_name; }
			set
			{
				this.OnPropertyValueChange("dept_name");
				this._dept_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("dept_guid")]
		public string dept_guid
		{
			get { return _dept_guid; }
			set
			{
				this.OnPropertyValueChange("dept_guid");
				this._dept_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("remark")]
		public string remark
		{
			get { return _remark; }
			set
			{
				this.OnPropertyValueChange("remark");
				this._remark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_hour")]
		public decimal? plan_hour
		{
			get { return _plan_hour; }
			set
			{
				this.OnPropertyValueChange("plan_hour");
				this._plan_hour = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_hour")]
		public decimal? act_hour
		{
			get { return _act_hour; }
			set
			{
				this.OnPropertyValueChange("act_hour");
				this._act_hour = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.wbs_guid,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.wbs_id,
				_.wbs_guid,
				_.proj_id,
				_.proj_guid,
				_.obs_id,
				_.obs_guid,
				_.seq_num,
				_.est_wt,
				_.complete_pct,
				_.proj_node_flag,
				_.sum_data_flag,
				_.status_code,
				_.wbs_short_name,
				_.wbs_name,
				_.phase_id,
				_.parent_wbs_id,
				_.parent_wbs_guid,
				_.ev_user_pct,
				_.ev_etc_user_value,
				_.orig_cost,
				_.user_cost1,
				_.indep_remain_total_cost,
				_.ann_dscnt_rate_pct,
				_.dscnt_period_type,
				_.indep_remain_work_qty,
				_.anticip_start_date,
				_.anticip_end_date,
				_.ev_compute_type,
				_.ev_etc_compute_type,
				_.guid,
				_.tmpl_guid,
				_.p3ec_wbs_id,
				_.p3ec_parentwbs_id,
				_.p3ec_flag,
				_.treelevel,
				_.haschild,
				_.discolor,
				_.target_start_date,
				_.target_end_date,
				_.expect_start_date,
				_.expect_end_date,
				_.act_start_date,
				_.act_end_date,
				_.SysOrNot,
				_.allowModifyTaskOrNot,
				_.complete_pct_type,
				_.target_drtn_hr_cnt,
				_.remain_drtn_hr_cnt,
				_.update_date,
				_.start_date,
				_.end_date,
				_.LongCode,
				_.plan_id,
				_.plan_guid,
				_.est_wt_pct,
				_.require_start_date,
				_.require_end_date,
				_.main_wbs_guid,
				_.bcws_cost,
				_.bcwp_cost,
				_.acwp_cost,
				_.budget_cost,
				_.reghumanid,
				_.reghumanname,
				_.rsrc_guid,
				_.rsrc_name,
				_.responsibleid,
				_.responsiblename,
				_.update_user,
				_.create_date,
				_.create_user,
				_.delete_session_id,
				_.delete_date,
				_.target_complete_pct,
				_.period_target_complete_pct,
				_.restart_date,
				_.reend_date,
				_.plan_pct,
				_.wbs_guid_before,
				_.dept_name,
				_.dept_guid,
				_.remark,
				_.plan_hour,
				_.act_hour,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._wbs_id,
				this._wbs_guid,
				this._proj_id,
				this._proj_guid,
				this._obs_id,
				this._obs_guid,
				this._seq_num,
				this._est_wt,
				this._complete_pct,
				this._proj_node_flag,
				this._sum_data_flag,
				this._status_code,
				this._wbs_short_name,
				this._wbs_name,
				this._phase_id,
				this._parent_wbs_id,
				this._parent_wbs_guid,
				this._ev_user_pct,
				this._ev_etc_user_value,
				this._orig_cost,
				this._user_cost1,
				this._indep_remain_total_cost,
				this._ann_dscnt_rate_pct,
				this._dscnt_period_type,
				this._indep_remain_work_qty,
				this._anticip_start_date,
				this._anticip_end_date,
				this._ev_compute_type,
				this._ev_etc_compute_type,
				this._guid,
				this._tmpl_guid,
				this._p3ec_wbs_id,
				this._p3ec_parentwbs_id,
				this._p3ec_flag,
				this._treelevel,
				this._haschild,
				this._discolor,
				this._target_start_date,
				this._target_end_date,
				this._expect_start_date,
				this._expect_end_date,
				this._act_start_date,
				this._act_end_date,
				this._SysOrNot,
				this._allowModifyTaskOrNot,
				this._complete_pct_type,
				this._target_drtn_hr_cnt,
				this._remain_drtn_hr_cnt,
				this._update_date,
				this._start_date,
				this._end_date,
				this._LongCode,
				this._plan_id,
				this._plan_guid,
				this._est_wt_pct,
				this._require_start_date,
				this._require_end_date,
				this._main_wbs_guid,
				this._bcws_cost,
				this._bcwp_cost,
				this._acwp_cost,
				this._budget_cost,
				this._reghumanid,
				this._reghumanname,
				this._rsrc_guid,
				this._rsrc_name,
				this._responsibleid,
				this._responsiblename,
				this._update_user,
				this._create_date,
				this._create_user,
				this._delete_session_id,
				this._delete_date,
				this._target_complete_pct,
				this._period_target_complete_pct,
				this._restart_date,
				this._reend_date,
				this._plan_pct,
				this._wbs_guid_before,
				this._dept_name,
				this._dept_guid,
				this._remark,
				this._plan_hour,
				this._act_hour,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "PLN_TempPROJWBS");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wbs_id = new Field("wbs_id", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wbs_guid = new Field("wbs_guid", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proj_id = new Field("proj_id", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proj_guid = new Field("proj_guid", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field obs_id = new Field("obs_id", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field obs_guid = new Field("obs_guid", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field seq_num = new Field("seq_num", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 权重
			/// </summary>
			public readonly static Field est_wt = new Field("est_wt", "PLN_TempPROJWBS", "权重");
			/// <summary>
			/// 完成百分比
			/// </summary>
			public readonly static Field complete_pct = new Field("complete_pct", "PLN_TempPROJWBS", "完成百分比");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proj_node_flag = new Field("proj_node_flag", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field sum_data_flag = new Field("sum_data_flag", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field status_code = new Field("status_code", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wbs_short_name = new Field("wbs_short_name", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wbs_name = new Field("wbs_name", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 尚不知用途
			/// </summary>
			public readonly static Field phase_id = new Field("phase_id", "PLN_TempPROJWBS", "尚不知用途");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field parent_wbs_id = new Field("parent_wbs_id", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field parent_wbs_guid = new Field("parent_wbs_guid", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ev_user_pct = new Field("ev_user_pct", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ev_etc_user_value = new Field("ev_etc_user_value", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field orig_cost = new Field("orig_cost", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field user_cost1 = new Field("user_cost1", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field indep_remain_total_cost = new Field("indep_remain_total_cost", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ann_dscnt_rate_pct = new Field("ann_dscnt_rate_pct", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field dscnt_period_type = new Field("dscnt_period_type", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field indep_remain_work_qty = new Field("indep_remain_work_qty", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field anticip_start_date = new Field("anticip_start_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field anticip_end_date = new Field("anticip_end_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ev_compute_type = new Field("ev_compute_type", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ev_etc_compute_type = new Field("ev_etc_compute_type", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field guid = new Field("guid", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field tmpl_guid = new Field("tmpl_guid", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field p3ec_wbs_id = new Field("p3ec_wbs_id", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field p3ec_parentwbs_id = new Field("p3ec_parentwbs_id", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field p3ec_flag = new Field("p3ec_flag", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field treelevel = new Field("treelevel", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field haschild = new Field("haschild", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field discolor = new Field("discolor", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_start_date = new Field("target_start_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_end_date = new Field("target_end_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field expect_start_date = new Field("expect_start_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field expect_end_date = new Field("expect_end_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_start_date = new Field("act_start_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_end_date = new Field("act_end_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 是否是系统生成,不能改变结构的,1是,0否
			/// </summary>
			public readonly static Field SysOrNot = new Field("SysOrNot", "PLN_TempPROJWBS", "是否是系统生成,不能改变结构的,1是,0否");
			/// <summary>
			/// 是否允许增、删task，1允许，0不允许
			/// </summary>
			public readonly static Field allowModifyTaskOrNot = new Field("allowModifyTaskOrNot", "PLN_TempPROJWBS", "是否允许增、删task，1允许，0不允许");
			/// <summary>
			/// 进度计算的方式 1、基于task；2、基于填报；3、基于里程碑点
			/// </summary>
			public readonly static Field complete_pct_type = new Field("complete_pct_type", "PLN_TempPROJWBS", "进度计算的方式 1、基于task；2、基于填报；3、基于里程碑点");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_drtn_hr_cnt = new Field("target_drtn_hr_cnt", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field remain_drtn_hr_cnt = new Field("remain_drtn_hr_cnt", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field update_date = new Field("update_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field start_date = new Field("start_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field end_date = new Field("end_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LongCode = new Field("LongCode", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_id = new Field("plan_id", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_guid = new Field("plan_guid", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field est_wt_pct = new Field("est_wt_pct", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field require_start_date = new Field("require_start_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field require_end_date = new Field("require_end_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 发包后主计划的WBS 主键
			/// </summary>
			public readonly static Field main_wbs_guid = new Field("main_wbs_guid", "PLN_TempPROJWBS", "发包后主计划的WBS 主键");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field bcws_cost = new Field("bcws_cost", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field bcwp_cost = new Field("bcwp_cost", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field acwp_cost = new Field("acwp_cost", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field budget_cost = new Field("budget_cost", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field reghumanid = new Field("reghumanid", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field reghumanname = new Field("reghumanname", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field rsrc_guid = new Field("rsrc_guid", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field rsrc_name = new Field("rsrc_name", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field responsibleid = new Field("responsibleid", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field responsiblename = new Field("responsiblename", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field update_user = new Field("update_user", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field create_date = new Field("create_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field create_user = new Field("create_user", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field delete_session_id = new Field("delete_session_id", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field delete_date = new Field("delete_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_complete_pct = new Field("target_complete_pct", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field period_target_complete_pct = new Field("period_target_complete_pct", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field restart_date = new Field("restart_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field reend_date = new Field("reend_date", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_pct = new Field("plan_pct", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wbs_guid_before = new Field("wbs_guid_before", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field dept_name = new Field("dept_name", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field dept_guid = new Field("dept_guid", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field remark = new Field("remark", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_hour = new Field("plan_hour", "PLN_TempPROJWBS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_hour = new Field("act_hour", "PLN_TempPROJWBS", "");
		}
		#endregion
	}
}