//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace JJWBSService.Modes
{
	/// <summary>
	/// 实体类PLN_Tepmtask。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("PLN_Tepmtask")]
	[Serializable]
	public partial class PLN_Tepmtask : Entity
	{
		#region Model
		private int _task_id;
		private string _task_guid;
		private int _proj_id;
		private string _proj_guid;
		private int _wbs_id;
		private string _wbs_guid;
		private int? _clndr_id;
		private string _clndr_guid;
		private int? _plan_id;
		private string _plan_guid;
		private int? _seq_num;
		private int? _parent_task_id;
		private string _parent_guid;
		private decimal? _est_wt;
		private decimal? _complete_pct;
		private string _rev_fdbk_flag;
		private string _lock_plan_flag;
		private string _auto_compute_act_flag;
		private string _complete_pct_type;
		private string _task_type;
		private string _duration_type;
		private string _review_type;
		private string _status_code;
		private string _task_code;
		private string _task_name;
		private string _rsrc_name;
		private int? _rsrc_id;
		private string _rsrc_guid;
		private decimal? _total_float_hr_cnt;
		private decimal? _free_float_hr_cnt;
		private decimal? _target_drtn_hr_cnt;
		private decimal? _act_drtn_hr_cnt;
		private decimal? _remain_drtn_hr_cnt;
		private decimal? _act_work_qty;
		private decimal? _remain_work_qty;
		private decimal? _target_work_qty;
		private decimal? _target_equip_qty;
		private decimal? _act_equip_qty;
		private decimal? _remain_equip_qty;
		private string _cstr_type;
		private DateTime? _cstr_date;
		private DateTime? _late_start_date;
		private DateTime? _late_end_date;
		private DateTime? _early_start_date;
		private DateTime? _early_end_date;
		private DateTime? _restart_date;
		private DateTime? _reend_date;
		private DateTime? _review_end_date;
		private DateTime? _rem_late_start_date;
		private DateTime? _rem_late_end_date;
		private string _priority_type;
		private string _guid;
		private string _tmpl_guid;
		private DateTime? _cstr_date2;
		private string _cstr_type2;
		private decimal? _act_this_per_work_qty;
		private decimal? _act_this_per_equip_qty;
		private string _driving_path_flag;
		private int? _float_path;
		private int? _float_path_order;
		private DateTime? _suspend_date;
		private DateTime? _resume_date;
		private DateTime? _external_early_start_date;
		private DateTime? _external_late_end_date;
		private DateTime? _update_date;
		private string _update_user;
		private DateTime? _create_date;
		private int? _create_user_sid;
		private string _create_user;
		private int? _delete_session_id;
		private DateTime? _delete_date;
		private DateTime? _act_start_date;
		private DateTime? _act_end_date;
		private DateTime? _expect_start_date;
		private DateTime? _expect_end_date;
		private DateTime? _target_start_date;
		private DateTime? _target_end_date;
		private bool? _SysOrNot;
		private int? _rec_type;
		private int? _temp_id;
		private int? _p3ec_flag;
		private int? _p3ec_task_id;
		private DateTime? _data_date;
		private DateTime? _start_date;
		private DateTime? _end_date;
		private int? _plan_task_id_befor;
		private string _plan_task_guid_before;
		private string _memo;
		private int? _module_type;
		private string _plan_actvcode_guid;
		private int? _plan_actvcode_id;
		private string _parent_task_plan_guid;
		private decimal? _est_wt_pct;
		private string _curve_guid;
		private string _feedback_pct_type;
		private DateTime? _baseline_start_date;
		private DateTime? _baseline_end_date;
		private DateTime? _baseline2_start_date;
		private DateTime? _baseline2_end_date;
		private DateTime? _baseline3_start_date;
		private DateTime? _baseline3_end_date;
		private string _progress_rsrc_unit_name;
		private decimal? _progress_rsrc_unit_price;
		private decimal? _target_progress_rsrc_cost;
		private decimal? _act_progress_rsrc_cost;
		private decimal? _remain_progress_rsrc_cost;
		private string _target_progress_rsrc_curv;
		private string _act_progress_rsrc_curv;
		private string _remain_progress_rsrc_curv;
		private string _target_progress_rsrc_guid;
		private string _target_progress_rsrc_code;
		private decimal? _target_progress_rsrc_qty;
		private decimal? _act_progress_rsrc_qty;
		private decimal? _remain_progress_rsrc_qty;
		private string _videoUrl;
		private decimal? _bcws_cost;
		private decimal? _bcwp_cost;
		private decimal? _acwp_cost;
		private int? _istopbreakdown;
		private float? _budget_cost;
		private int? _attach_flag;
		private int? _UPDATE_SESSION_ID;
		private decimal? _target_complete_pct;
		private decimal? _period_target_complete_pct;
		private string _important_node_flag;
		private decimal? _plan_pct;
		private DateTime? _feedback_data_date;
		private string _dept_name;
		private string _dept_guid;
		private string _remark;
		private decimal? _plan_hour;
		private decimal? _act_hour;
		private string _TempTask_code;

		/// <summary>
		/// 
		/// </summary>
		[Field("task_id")]
		public int task_id
		{
			get { return _task_id; }
			set
			{
				this.OnPropertyValueChange("task_id");
				this._task_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("task_guid")]
		public string task_guid
		{
			get { return _task_guid; }
			set
			{
				this.OnPropertyValueChange("task_guid");
				this._task_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proj_id")]
		public int proj_id
		{
			get { return _proj_id; }
			set
			{
				this.OnPropertyValueChange("proj_id");
				this._proj_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proj_guid")]
		public string proj_guid
		{
			get { return _proj_guid; }
			set
			{
				this.OnPropertyValueChange("proj_guid");
				this._proj_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("wbs_id")]
		public int wbs_id
		{
			get { return _wbs_id; }
			set
			{
				this.OnPropertyValueChange("wbs_id");
				this._wbs_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("wbs_guid")]
		public string wbs_guid
		{
			get { return _wbs_guid; }
			set
			{
				this.OnPropertyValueChange("wbs_guid");
				this._wbs_guid = value;
			}
		}
		/// <summary>
		/// 日历
		/// </summary>
		[Field("clndr_id")]
		public int? clndr_id
		{
			get { return _clndr_id; }
			set
			{
				this.OnPropertyValueChange("clndr_id");
				this._clndr_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("clndr_guid")]
		public string clndr_guid
		{
			get { return _clndr_guid; }
			set
			{
				this.OnPropertyValueChange("clndr_guid");
				this._clndr_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_id")]
		public int? plan_id
		{
			get { return _plan_id; }
			set
			{
				this.OnPropertyValueChange("plan_id");
				this._plan_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_guid")]
		public string plan_guid
		{
			get { return _plan_guid; }
			set
			{
				this.OnPropertyValueChange("plan_guid");
				this._plan_guid = value;
			}
		}
		/// <summary>
		/// 排序号
		/// </summary>
		[Field("seq_num")]
		public int? seq_num
		{
			get { return _seq_num; }
			set
			{
				this.OnPropertyValueChange("seq_num");
				this._seq_num = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("parent_task_id")]
		public int? parent_task_id
		{
			get { return _parent_task_id; }
			set
			{
				this.OnPropertyValueChange("parent_task_id");
				this._parent_task_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("parent_guid")]
		public string parent_guid
		{
			get { return _parent_guid; }
			set
			{
				this.OnPropertyValueChange("parent_guid");
				this._parent_guid = value;
			}
		}
		/// <summary>
		/// 权重
		/// </summary>
		[Field("est_wt")]
		public decimal? est_wt
		{
			get { return _est_wt; }
			set
			{
				this.OnPropertyValueChange("est_wt");
				this._est_wt = value;
			}
		}
		/// <summary>
		/// 完成百分比
		/// </summary>
		[Field("complete_pct")]
		public decimal? complete_pct
		{
			get { return _complete_pct; }
			set
			{
				this.OnPropertyValueChange("complete_pct");
				this._complete_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("rev_fdbk_flag")]
		public string rev_fdbk_flag
		{
			get { return _rev_fdbk_flag; }
			set
			{
				this.OnPropertyValueChange("rev_fdbk_flag");
				this._rev_fdbk_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("lock_plan_flag")]
		public string lock_plan_flag
		{
			get { return _lock_plan_flag; }
			set
			{
				this.OnPropertyValueChange("lock_plan_flag");
				this._lock_plan_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("auto_compute_act_flag")]
		public string auto_compute_act_flag
		{
			get { return _auto_compute_act_flag; }
			set
			{
				this.OnPropertyValueChange("auto_compute_act_flag");
				this._auto_compute_act_flag = value;
			}
		}
		/// <summary>
		/// 完成百分比计算类型，原值(&#39;CP_Drtn&#39;)，现改为true为关联步骤，false为不关联
		/// </summary>
		[Field("complete_pct_type")]
		public string complete_pct_type
		{
			get { return _complete_pct_type; }
			set
			{
				this.OnPropertyValueChange("complete_pct_type");
				this._complete_pct_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("task_type")]
		public string task_type
		{
			get { return _task_type; }
			set
			{
				this.OnPropertyValueChange("task_type");
				this._task_type = value;
			}
		}
		/// <summary>
		/// 工期类型
		/// </summary>
		[Field("duration_type")]
		public string duration_type
		{
			get { return _duration_type; }
			set
			{
				this.OnPropertyValueChange("duration_type");
				this._duration_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("review_type")]
		public string review_type
		{
			get { return _review_type; }
			set
			{
				this.OnPropertyValueChange("review_type");
				this._review_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("status_code")]
		public string status_code
		{
			get { return _status_code; }
			set
			{
				this.OnPropertyValueChange("status_code");
				this._status_code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("task_code")]
		public string task_code
		{
			get { return _task_code; }
			set
			{
				this.OnPropertyValueChange("task_code");
				this._task_code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("task_name")]
		public string task_name
		{
			get { return _task_name; }
			set
			{
				this.OnPropertyValueChange("task_name");
				this._task_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("rsrc_name")]
		public string rsrc_name
		{
			get { return _rsrc_name; }
			set
			{
				this.OnPropertyValueChange("rsrc_name");
				this._rsrc_name = value;
			}
		}
		/// <summary>
		/// 资源id
		/// </summary>
		[Field("rsrc_id")]
		public int? rsrc_id
		{
			get { return _rsrc_id; }
			set
			{
				this.OnPropertyValueChange("rsrc_id");
				this._rsrc_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("rsrc_guid")]
		public string rsrc_guid
		{
			get { return _rsrc_guid; }
			set
			{
				this.OnPropertyValueChange("rsrc_guid");
				this._rsrc_guid = value;
			}
		}
		/// <summary>
		/// TF
		/// </summary>
		[Field("total_float_hr_cnt")]
		public decimal? total_float_hr_cnt
		{
			get { return _total_float_hr_cnt; }
			set
			{
				this.OnPropertyValueChange("total_float_hr_cnt");
				this._total_float_hr_cnt = value;
			}
		}
		/// <summary>
		/// FF
		/// </summary>
		[Field("free_float_hr_cnt")]
		public decimal? free_float_hr_cnt
		{
			get { return _free_float_hr_cnt; }
			set
			{
				this.OnPropertyValueChange("free_float_hr_cnt");
				this._free_float_hr_cnt = value;
			}
		}
		/// <summary>
		/// 原定工期
		/// </summary>
		[Field("target_drtn_hr_cnt")]
		public decimal? target_drtn_hr_cnt
		{
			get { return _target_drtn_hr_cnt; }
			set
			{
				this.OnPropertyValueChange("target_drtn_hr_cnt");
				this._target_drtn_hr_cnt = value;
			}
		}
		/// <summary>
		/// 实际工期
		/// </summary>
		[Field("act_drtn_hr_cnt")]
		public decimal? act_drtn_hr_cnt
		{
			get { return _act_drtn_hr_cnt; }
			set
			{
				this.OnPropertyValueChange("act_drtn_hr_cnt");
				this._act_drtn_hr_cnt = value;
			}
		}
		/// <summary>
		/// 尚需工期
		/// </summary>
		[Field("remain_drtn_hr_cnt")]
		public decimal? remain_drtn_hr_cnt
		{
			get { return _remain_drtn_hr_cnt; }
			set
			{
				this.OnPropertyValueChange("remain_drtn_hr_cnt");
				this._remain_drtn_hr_cnt = value;
			}
		}
		/// <summary>
		/// 实际工作天数
		/// </summary>
		[Field("act_work_qty")]
		public decimal? act_work_qty
		{
			get { return _act_work_qty; }
			set
			{
				this.OnPropertyValueChange("act_work_qty");
				this._act_work_qty = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("remain_work_qty")]
		public decimal? remain_work_qty
		{
			get { return _remain_work_qty; }
			set
			{
				this.OnPropertyValueChange("remain_work_qty");
				this._remain_work_qty = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_work_qty")]
		public decimal? target_work_qty
		{
			get { return _target_work_qty; }
			set
			{
				this.OnPropertyValueChange("target_work_qty");
				this._target_work_qty = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_equip_qty")]
		public decimal? target_equip_qty
		{
			get { return _target_equip_qty; }
			set
			{
				this.OnPropertyValueChange("target_equip_qty");
				this._target_equip_qty = value;
			}
		}
		/// <summary>
		/// 实际时
		/// </summary>
		[Field("act_equip_qty")]
		public decimal? act_equip_qty
		{
			get { return _act_equip_qty; }
			set
			{
				this.OnPropertyValueChange("act_equip_qty");
				this._act_equip_qty = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("remain_equip_qty")]
		public decimal? remain_equip_qty
		{
			get { return _remain_equip_qty; }
			set
			{
				this.OnPropertyValueChange("remain_equip_qty");
				this._remain_equip_qty = value;
			}
		}
		/// <summary>
		/// 限制条件1
		/// </summary>
		[Field("cstr_type")]
		public string cstr_type
		{
			get { return _cstr_type; }
			set
			{
				this.OnPropertyValueChange("cstr_type");
				this._cstr_type = value;
			}
		}
		/// <summary>
		/// 限制条件1日期
		/// </summary>
		[Field("cstr_date")]
		public DateTime? cstr_date
		{
			get { return _cstr_date; }
			set
			{
				this.OnPropertyValueChange("cstr_date");
				this._cstr_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("late_start_date")]
		public DateTime? late_start_date
		{
			get { return _late_start_date; }
			set
			{
				this.OnPropertyValueChange("late_start_date");
				this._late_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("late_end_date")]
		public DateTime? late_end_date
		{
			get { return _late_end_date; }
			set
			{
				this.OnPropertyValueChange("late_end_date");
				this._late_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("early_start_date")]
		public DateTime? early_start_date
		{
			get { return _early_start_date; }
			set
			{
				this.OnPropertyValueChange("early_start_date");
				this._early_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("early_end_date")]
		public DateTime? early_end_date
		{
			get { return _early_end_date; }
			set
			{
				this.OnPropertyValueChange("early_end_date");
				this._early_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("restart_date")]
		public DateTime? restart_date
		{
			get { return _restart_date; }
			set
			{
				this.OnPropertyValueChange("restart_date");
				this._restart_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("reend_date")]
		public DateTime? reend_date
		{
			get { return _reend_date; }
			set
			{
				this.OnPropertyValueChange("reend_date");
				this._reend_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("review_end_date")]
		public DateTime? review_end_date
		{
			get { return _review_end_date; }
			set
			{
				this.OnPropertyValueChange("review_end_date");
				this._review_end_date = value;
			}
		}
		/// <summary>
		/// 尚需 最晚开始时间(逻辑计算相关)
		/// </summary>
		[Field("rem_late_start_date")]
		public DateTime? rem_late_start_date
		{
			get { return _rem_late_start_date; }
			set
			{
				this.OnPropertyValueChange("rem_late_start_date");
				this._rem_late_start_date = value;
			}
		}
		/// <summary>
		/// 尚需 最晚结束时间(逻辑计算相关)
		/// </summary>
		[Field("rem_late_end_date")]
		public DateTime? rem_late_end_date
		{
			get { return _rem_late_end_date; }
			set
			{
				this.OnPropertyValueChange("rem_late_end_date");
				this._rem_late_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("priority_type")]
		public string priority_type
		{
			get { return _priority_type; }
			set
			{
				this.OnPropertyValueChange("priority_type");
				this._priority_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("guid")]
		public string guid
		{
			get { return _guid; }
			set
			{
				this.OnPropertyValueChange("guid");
				this._guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("tmpl_guid")]
		public string tmpl_guid
		{
			get { return _tmpl_guid; }
			set
			{
				this.OnPropertyValueChange("tmpl_guid");
				this._tmpl_guid = value;
			}
		}
		/// <summary>
		/// 限制条件2日期
		/// </summary>
		[Field("cstr_date2")]
		public DateTime? cstr_date2
		{
			get { return _cstr_date2; }
			set
			{
				this.OnPropertyValueChange("cstr_date2");
				this._cstr_date2 = value;
			}
		}
		/// <summary>
		/// 限制条件2
		/// </summary>
		[Field("cstr_type2")]
		public string cstr_type2
		{
			get { return _cstr_type2; }
			set
			{
				this.OnPropertyValueChange("cstr_type2");
				this._cstr_type2 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_this_per_work_qty")]
		public decimal? act_this_per_work_qty
		{
			get { return _act_this_per_work_qty; }
			set
			{
				this.OnPropertyValueChange("act_this_per_work_qty");
				this._act_this_per_work_qty = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_this_per_equip_qty")]
		public decimal? act_this_per_equip_qty
		{
			get { return _act_this_per_equip_qty; }
			set
			{
				this.OnPropertyValueChange("act_this_per_equip_qty");
				this._act_this_per_equip_qty = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("driving_path_flag")]
		public string driving_path_flag
		{
			get { return _driving_path_flag; }
			set
			{
				this.OnPropertyValueChange("driving_path_flag");
				this._driving_path_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("float_path")]
		public int? float_path
		{
			get { return _float_path; }
			set
			{
				this.OnPropertyValueChange("float_path");
				this._float_path = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("float_path_order")]
		public int? float_path_order
		{
			get { return _float_path_order; }
			set
			{
				this.OnPropertyValueChange("float_path_order");
				this._float_path_order = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("suspend_date")]
		public DateTime? suspend_date
		{
			get { return _suspend_date; }
			set
			{
				this.OnPropertyValueChange("suspend_date");
				this._suspend_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("resume_date")]
		public DateTime? resume_date
		{
			get { return _resume_date; }
			set
			{
				this.OnPropertyValueChange("resume_date");
				this._resume_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("external_early_start_date")]
		public DateTime? external_early_start_date
		{
			get { return _external_early_start_date; }
			set
			{
				this.OnPropertyValueChange("external_early_start_date");
				this._external_early_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("external_late_end_date")]
		public DateTime? external_late_end_date
		{
			get { return _external_late_end_date; }
			set
			{
				this.OnPropertyValueChange("external_late_end_date");
				this._external_late_end_date = value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		[Field("update_date")]
		public DateTime? update_date
		{
			get { return _update_date; }
			set
			{
				this.OnPropertyValueChange("update_date");
				this._update_date = value;
			}
		}
		/// <summary>
		/// 更新人
		/// </summary>
		[Field("update_user")]
		public string update_user
		{
			get { return _update_user; }
			set
			{
				this.OnPropertyValueChange("update_user");
				this._update_user = value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		[Field("create_date")]
		public DateTime? create_date
		{
			get { return _create_date; }
			set
			{
				this.OnPropertyValueChange("create_date");
				this._create_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("create_user_sid")]
		public int? create_user_sid
		{
			get { return _create_user_sid; }
			set
			{
				this.OnPropertyValueChange("create_user_sid");
				this._create_user_sid = value;
			}
		}
		/// <summary>
		/// 创建人
		/// </summary>
		[Field("create_user")]
		public string create_user
		{
			get { return _create_user; }
			set
			{
				this.OnPropertyValueChange("create_user");
				this._create_user = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("delete_session_id")]
		public int? delete_session_id
		{
			get { return _delete_session_id; }
			set
			{
				this.OnPropertyValueChange("delete_session_id");
				this._delete_session_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("delete_date")]
		public DateTime? delete_date
		{
			get { return _delete_date; }
			set
			{
				this.OnPropertyValueChange("delete_date");
				this._delete_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_start_date")]
		public DateTime? act_start_date
		{
			get { return _act_start_date; }
			set
			{
				this.OnPropertyValueChange("act_start_date");
				this._act_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_end_date")]
		public DateTime? act_end_date
		{
			get { return _act_end_date; }
			set
			{
				this.OnPropertyValueChange("act_end_date");
				this._act_end_date = value;
			}
		}
		/// <summary>
		/// 计划开始
		/// </summary>
		[Field("expect_start_date")]
		public DateTime? expect_start_date
		{
			get { return _expect_start_date; }
			set
			{
				this.OnPropertyValueChange("expect_start_date");
				this._expect_start_date = value;
			}
		}
		/// <summary>
		/// 计划结束
		/// </summary>
		[Field("expect_end_date")]
		public DateTime? expect_end_date
		{
			get { return _expect_end_date; }
			set
			{
				this.OnPropertyValueChange("expect_end_date");
				this._expect_end_date = value;
			}
		}
		/// <summary>
		/// 计划开始时间
		/// </summary>
		[Field("target_start_date")]
		public DateTime? target_start_date
		{
			get { return _target_start_date; }
			set
			{
				this.OnPropertyValueChange("target_start_date");
				this._target_start_date = value;
			}
		}
		/// <summary>
		/// 计划结束时间
		/// </summary>
		[Field("target_end_date")]
		public DateTime? target_end_date
		{
			get { return _target_end_date; }
			set
			{
				this.OnPropertyValueChange("target_end_date");
				this._target_end_date = value;
			}
		}
		/// <summary>
		/// 是否是系统生成,不能改变结构的,1是,0否
		/// </summary>
		[Field("SysOrNot")]
		public bool? SysOrNot
		{
			get { return _SysOrNot; }
			set
			{
				this.OnPropertyValueChange("SysOrNot");
				this._SysOrNot = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("rec_type")]
		public int? rec_type
		{
			get { return _rec_type; }
			set
			{
				this.OnPropertyValueChange("rec_type");
				this._rec_type = value;
			}
		}
		/// <summary>
		/// 从模版对应id
		/// </summary>
		[Field("temp_id")]
		public int? temp_id
		{
			get { return _temp_id; }
			set
			{
				this.OnPropertyValueChange("temp_id");
				this._temp_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("p3ec_flag")]
		public int? p3ec_flag
		{
			get { return _p3ec_flag; }
			set
			{
				this.OnPropertyValueChange("p3ec_flag");
				this._p3ec_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("p3ec_task_id")]
		public int? p3ec_task_id
		{
			get { return _p3ec_task_id; }
			set
			{
				this.OnPropertyValueChange("p3ec_task_id");
				this._p3ec_task_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("data_date")]
		public DateTime? data_date
		{
			get { return _data_date; }
			set
			{
				this.OnPropertyValueChange("data_date");
				this._data_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("start_date")]
		public DateTime? start_date
		{
			get { return _start_date; }
			set
			{
				this.OnPropertyValueChange("start_date");
				this._start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("end_date")]
		public DateTime? end_date
		{
			get { return _end_date; }
			set
			{
				this.OnPropertyValueChange("end_date");
				this._end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_task_id_befor")]
		public int? plan_task_id_befor
		{
			get { return _plan_task_id_befor; }
			set
			{
				this.OnPropertyValueChange("plan_task_id_befor");
				this._plan_task_id_befor = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_task_guid_before")]
		public string plan_task_guid_before
		{
			get { return _plan_task_guid_before; }
			set
			{
				this.OnPropertyValueChange("plan_task_guid_before");
				this._plan_task_guid_before = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("memo")]
		public string memo
		{
			get { return _memo; }
			set
			{
				this.OnPropertyValueChange("memo");
				this._memo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("module_type")]
		public int? module_type
		{
			get { return _module_type; }
			set
			{
				this.OnPropertyValueChange("module_type");
				this._module_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_actvcode_guid")]
		public string plan_actvcode_guid
		{
			get { return _plan_actvcode_guid; }
			set
			{
				this.OnPropertyValueChange("plan_actvcode_guid");
				this._plan_actvcode_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_actvcode_id")]
		public int? plan_actvcode_id
		{
			get { return _plan_actvcode_id; }
			set
			{
				this.OnPropertyValueChange("plan_actvcode_id");
				this._plan_actvcode_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("parent_task_plan_guid")]
		public string parent_task_plan_guid
		{
			get { return _parent_task_plan_guid; }
			set
			{
				this.OnPropertyValueChange("parent_task_plan_guid");
				this._parent_task_plan_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("est_wt_pct")]
		public decimal? est_wt_pct
		{
			get { return _est_wt_pct; }
			set
			{
				this.OnPropertyValueChange("est_wt_pct");
				this._est_wt_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("curve_guid")]
		public string curve_guid
		{
			get { return _curve_guid; }
			set
			{
				this.OnPropertyValueChange("curve_guid");
				this._curve_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("feedback_pct_type")]
		public string feedback_pct_type
		{
			get { return _feedback_pct_type; }
			set
			{
				this.OnPropertyValueChange("feedback_pct_type");
				this._feedback_pct_type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("baseline_start_date")]
		public DateTime? baseline_start_date
		{
			get { return _baseline_start_date; }
			set
			{
				this.OnPropertyValueChange("baseline_start_date");
				this._baseline_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("baseline_end_date")]
		public DateTime? baseline_end_date
		{
			get { return _baseline_end_date; }
			set
			{
				this.OnPropertyValueChange("baseline_end_date");
				this._baseline_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("baseline2_start_date")]
		public DateTime? baseline2_start_date
		{
			get { return _baseline2_start_date; }
			set
			{
				this.OnPropertyValueChange("baseline2_start_date");
				this._baseline2_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("baseline2_end_date")]
		public DateTime? baseline2_end_date
		{
			get { return _baseline2_end_date; }
			set
			{
				this.OnPropertyValueChange("baseline2_end_date");
				this._baseline2_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("baseline3_start_date")]
		public DateTime? baseline3_start_date
		{
			get { return _baseline3_start_date; }
			set
			{
				this.OnPropertyValueChange("baseline3_start_date");
				this._baseline3_start_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("baseline3_end_date")]
		public DateTime? baseline3_end_date
		{
			get { return _baseline3_end_date; }
			set
			{
				this.OnPropertyValueChange("baseline3_end_date");
				this._baseline3_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("progress_rsrc_unit_name")]
		public string progress_rsrc_unit_name
		{
			get { return _progress_rsrc_unit_name; }
			set
			{
				this.OnPropertyValueChange("progress_rsrc_unit_name");
				this._progress_rsrc_unit_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("progress_rsrc_unit_price")]
		public decimal? progress_rsrc_unit_price
		{
			get { return _progress_rsrc_unit_price; }
			set
			{
				this.OnPropertyValueChange("progress_rsrc_unit_price");
				this._progress_rsrc_unit_price = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_progress_rsrc_cost")]
		public decimal? target_progress_rsrc_cost
		{
			get { return _target_progress_rsrc_cost; }
			set
			{
				this.OnPropertyValueChange("target_progress_rsrc_cost");
				this._target_progress_rsrc_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_progress_rsrc_cost")]
		public decimal? act_progress_rsrc_cost
		{
			get { return _act_progress_rsrc_cost; }
			set
			{
				this.OnPropertyValueChange("act_progress_rsrc_cost");
				this._act_progress_rsrc_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("remain_progress_rsrc_cost")]
		public decimal? remain_progress_rsrc_cost
		{
			get { return _remain_progress_rsrc_cost; }
			set
			{
				this.OnPropertyValueChange("remain_progress_rsrc_cost");
				this._remain_progress_rsrc_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_progress_rsrc_curv")]
		public string target_progress_rsrc_curv
		{
			get { return _target_progress_rsrc_curv; }
			set
			{
				this.OnPropertyValueChange("target_progress_rsrc_curv");
				this._target_progress_rsrc_curv = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_progress_rsrc_curv")]
		public string act_progress_rsrc_curv
		{
			get { return _act_progress_rsrc_curv; }
			set
			{
				this.OnPropertyValueChange("act_progress_rsrc_curv");
				this._act_progress_rsrc_curv = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("remain_progress_rsrc_curv")]
		public string remain_progress_rsrc_curv
		{
			get { return _remain_progress_rsrc_curv; }
			set
			{
				this.OnPropertyValueChange("remain_progress_rsrc_curv");
				this._remain_progress_rsrc_curv = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_progress_rsrc_guid")]
		public string target_progress_rsrc_guid
		{
			get { return _target_progress_rsrc_guid; }
			set
			{
				this.OnPropertyValueChange("target_progress_rsrc_guid");
				this._target_progress_rsrc_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_progress_rsrc_code")]
		public string target_progress_rsrc_code
		{
			get { return _target_progress_rsrc_code; }
			set
			{
				this.OnPropertyValueChange("target_progress_rsrc_code");
				this._target_progress_rsrc_code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_progress_rsrc_qty")]
		public decimal? target_progress_rsrc_qty
		{
			get { return _target_progress_rsrc_qty; }
			set
			{
				this.OnPropertyValueChange("target_progress_rsrc_qty");
				this._target_progress_rsrc_qty = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_progress_rsrc_qty")]
		public decimal? act_progress_rsrc_qty
		{
			get { return _act_progress_rsrc_qty; }
			set
			{
				this.OnPropertyValueChange("act_progress_rsrc_qty");
				this._act_progress_rsrc_qty = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("remain_progress_rsrc_qty")]
		public decimal? remain_progress_rsrc_qty
		{
			get { return _remain_progress_rsrc_qty; }
			set
			{
				this.OnPropertyValueChange("remain_progress_rsrc_qty");
				this._remain_progress_rsrc_qty = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("videoUrl")]
		public string videoUrl
		{
			get { return _videoUrl; }
			set
			{
				this.OnPropertyValueChange("videoUrl");
				this._videoUrl = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("bcws_cost")]
		public decimal? bcws_cost
		{
			get { return _bcws_cost; }
			set
			{
				this.OnPropertyValueChange("bcws_cost");
				this._bcws_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("bcwp_cost")]
		public decimal? bcwp_cost
		{
			get { return _bcwp_cost; }
			set
			{
				this.OnPropertyValueChange("bcwp_cost");
				this._bcwp_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("acwp_cost")]
		public decimal? acwp_cost
		{
			get { return _acwp_cost; }
			set
			{
				this.OnPropertyValueChange("acwp_cost");
				this._acwp_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("istopbreakdown")]
		public int? istopbreakdown
		{
			get { return _istopbreakdown; }
			set
			{
				this.OnPropertyValueChange("istopbreakdown");
				this._istopbreakdown = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("budget_cost")]
		public float? budget_cost
		{
			get { return _budget_cost; }
			set
			{
				this.OnPropertyValueChange("budget_cost");
				this._budget_cost = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("attach_flag")]
		public int? attach_flag
		{
			get { return _attach_flag; }
			set
			{
				this.OnPropertyValueChange("attach_flag");
				this._attach_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UPDATE_SESSION_ID")]
		public int? UPDATE_SESSION_ID
		{
			get { return _UPDATE_SESSION_ID; }
			set
			{
				this.OnPropertyValueChange("UPDATE_SESSION_ID");
				this._UPDATE_SESSION_ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_complete_pct")]
		public decimal? target_complete_pct
		{
			get { return _target_complete_pct; }
			set
			{
				this.OnPropertyValueChange("target_complete_pct");
				this._target_complete_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("period_target_complete_pct")]
		public decimal? period_target_complete_pct
		{
			get { return _period_target_complete_pct; }
			set
			{
				this.OnPropertyValueChange("period_target_complete_pct");
				this._period_target_complete_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("important_node_flag")]
		public string important_node_flag
		{
			get { return _important_node_flag; }
			set
			{
				this.OnPropertyValueChange("important_node_flag");
				this._important_node_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_pct")]
		public decimal? plan_pct
		{
			get { return _plan_pct; }
			set
			{
				this.OnPropertyValueChange("plan_pct");
				this._plan_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("feedback_data_date")]
		public DateTime? feedback_data_date
		{
			get { return _feedback_data_date; }
			set
			{
				this.OnPropertyValueChange("feedback_data_date");
				this._feedback_data_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("dept_name")]
		public string dept_name
		{
			get { return _dept_name; }
			set
			{
				this.OnPropertyValueChange("dept_name");
				this._dept_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("dept_guid")]
		public string dept_guid
		{
			get { return _dept_guid; }
			set
			{
				this.OnPropertyValueChange("dept_guid");
				this._dept_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("remark")]
		public string remark
		{
			get { return _remark; }
			set
			{
				this.OnPropertyValueChange("remark");
				this._remark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_hour")]
		public decimal? plan_hour
		{
			get { return _plan_hour; }
			set
			{
				this.OnPropertyValueChange("plan_hour");
				this._plan_hour = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_hour")]
		public decimal? act_hour
		{
			get { return _act_hour; }
			set
			{
				this.OnPropertyValueChange("act_hour");
				this._act_hour = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TempTask_code")]
		public string TempTask_code
		{
			get { return _TempTask_code; }
			set
			{
				this.OnPropertyValueChange("TempTask_code");
				this._TempTask_code = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.task_id,
				_.task_guid,
			};
		}
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.task_id;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.task_id,
				_.task_guid,
				_.proj_id,
				_.proj_guid,
				_.wbs_id,
				_.wbs_guid,
				_.clndr_id,
				_.clndr_guid,
				_.plan_id,
				_.plan_guid,
				_.seq_num,
				_.parent_task_id,
				_.parent_guid,
				_.est_wt,
				_.complete_pct,
				_.rev_fdbk_flag,
				_.lock_plan_flag,
				_.auto_compute_act_flag,
				_.complete_pct_type,
				_.task_type,
				_.duration_type,
				_.review_type,
				_.status_code,
				_.task_code,
				_.task_name,
				_.rsrc_name,
				_.rsrc_id,
				_.rsrc_guid,
				_.total_float_hr_cnt,
				_.free_float_hr_cnt,
				_.target_drtn_hr_cnt,
				_.act_drtn_hr_cnt,
				_.remain_drtn_hr_cnt,
				_.act_work_qty,
				_.remain_work_qty,
				_.target_work_qty,
				_.target_equip_qty,
				_.act_equip_qty,
				_.remain_equip_qty,
				_.cstr_type,
				_.cstr_date,
				_.late_start_date,
				_.late_end_date,
				_.early_start_date,
				_.early_end_date,
				_.restart_date,
				_.reend_date,
				_.review_end_date,
				_.rem_late_start_date,
				_.rem_late_end_date,
				_.priority_type,
				_.guid,
				_.tmpl_guid,
				_.cstr_date2,
				_.cstr_type2,
				_.act_this_per_work_qty,
				_.act_this_per_equip_qty,
				_.driving_path_flag,
				_.float_path,
				_.float_path_order,
				_.suspend_date,
				_.resume_date,
				_.external_early_start_date,
				_.external_late_end_date,
				_.update_date,
				_.update_user,
				_.create_date,
				_.create_user_sid,
				_.create_user,
				_.delete_session_id,
				_.delete_date,
				_.act_start_date,
				_.act_end_date,
				_.expect_start_date,
				_.expect_end_date,
				_.target_start_date,
				_.target_end_date,
				_.SysOrNot,
				_.rec_type,
				_.temp_id,
				_.p3ec_flag,
				_.p3ec_task_id,
				_.data_date,
				_.start_date,
				_.end_date,
				_.plan_task_id_befor,
				_.plan_task_guid_before,
				_.memo,
				_.module_type,
				_.plan_actvcode_guid,
				_.plan_actvcode_id,
				_.parent_task_plan_guid,
				_.est_wt_pct,
				_.curve_guid,
				_.feedback_pct_type,
				_.baseline_start_date,
				_.baseline_end_date,
				_.baseline2_start_date,
				_.baseline2_end_date,
				_.baseline3_start_date,
				_.baseline3_end_date,
				_.progress_rsrc_unit_name,
				_.progress_rsrc_unit_price,
				_.target_progress_rsrc_cost,
				_.act_progress_rsrc_cost,
				_.remain_progress_rsrc_cost,
				_.target_progress_rsrc_curv,
				_.act_progress_rsrc_curv,
				_.remain_progress_rsrc_curv,
				_.target_progress_rsrc_guid,
				_.target_progress_rsrc_code,
				_.target_progress_rsrc_qty,
				_.act_progress_rsrc_qty,
				_.remain_progress_rsrc_qty,
				_.videoUrl,
				_.bcws_cost,
				_.bcwp_cost,
				_.acwp_cost,
				_.istopbreakdown,
				_.budget_cost,
				_.attach_flag,
				_.UPDATE_SESSION_ID,
				_.target_complete_pct,
				_.period_target_complete_pct,
				_.important_node_flag,
				_.plan_pct,
				_.feedback_data_date,
				_.dept_name,
				_.dept_guid,
				_.remark,
				_.plan_hour,
				_.act_hour,
				_.TempTask_code,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._task_id,
				this._task_guid,
				this._proj_id,
				this._proj_guid,
				this._wbs_id,
				this._wbs_guid,
				this._clndr_id,
				this._clndr_guid,
				this._plan_id,
				this._plan_guid,
				this._seq_num,
				this._parent_task_id,
				this._parent_guid,
				this._est_wt,
				this._complete_pct,
				this._rev_fdbk_flag,
				this._lock_plan_flag,
				this._auto_compute_act_flag,
				this._complete_pct_type,
				this._task_type,
				this._duration_type,
				this._review_type,
				this._status_code,
				this._task_code,
				this._task_name,
				this._rsrc_name,
				this._rsrc_id,
				this._rsrc_guid,
				this._total_float_hr_cnt,
				this._free_float_hr_cnt,
				this._target_drtn_hr_cnt,
				this._act_drtn_hr_cnt,
				this._remain_drtn_hr_cnt,
				this._act_work_qty,
				this._remain_work_qty,
				this._target_work_qty,
				this._target_equip_qty,
				this._act_equip_qty,
				this._remain_equip_qty,
				this._cstr_type,
				this._cstr_date,
				this._late_start_date,
				this._late_end_date,
				this._early_start_date,
				this._early_end_date,
				this._restart_date,
				this._reend_date,
				this._review_end_date,
				this._rem_late_start_date,
				this._rem_late_end_date,
				this._priority_type,
				this._guid,
				this._tmpl_guid,
				this._cstr_date2,
				this._cstr_type2,
				this._act_this_per_work_qty,
				this._act_this_per_equip_qty,
				this._driving_path_flag,
				this._float_path,
				this._float_path_order,
				this._suspend_date,
				this._resume_date,
				this._external_early_start_date,
				this._external_late_end_date,
				this._update_date,
				this._update_user,
				this._create_date,
				this._create_user_sid,
				this._create_user,
				this._delete_session_id,
				this._delete_date,
				this._act_start_date,
				this._act_end_date,
				this._expect_start_date,
				this._expect_end_date,
				this._target_start_date,
				this._target_end_date,
				this._SysOrNot,
				this._rec_type,
				this._temp_id,
				this._p3ec_flag,
				this._p3ec_task_id,
				this._data_date,
				this._start_date,
				this._end_date,
				this._plan_task_id_befor,
				this._plan_task_guid_before,
				this._memo,
				this._module_type,
				this._plan_actvcode_guid,
				this._plan_actvcode_id,
				this._parent_task_plan_guid,
				this._est_wt_pct,
				this._curve_guid,
				this._feedback_pct_type,
				this._baseline_start_date,
				this._baseline_end_date,
				this._baseline2_start_date,
				this._baseline2_end_date,
				this._baseline3_start_date,
				this._baseline3_end_date,
				this._progress_rsrc_unit_name,
				this._progress_rsrc_unit_price,
				this._target_progress_rsrc_cost,
				this._act_progress_rsrc_cost,
				this._remain_progress_rsrc_cost,
				this._target_progress_rsrc_curv,
				this._act_progress_rsrc_curv,
				this._remain_progress_rsrc_curv,
				this._target_progress_rsrc_guid,
				this._target_progress_rsrc_code,
				this._target_progress_rsrc_qty,
				this._act_progress_rsrc_qty,
				this._remain_progress_rsrc_qty,
				this._videoUrl,
				this._bcws_cost,
				this._bcwp_cost,
				this._acwp_cost,
				this._istopbreakdown,
				this._budget_cost,
				this._attach_flag,
				this._UPDATE_SESSION_ID,
				this._target_complete_pct,
				this._period_target_complete_pct,
				this._important_node_flag,
				this._plan_pct,
				this._feedback_data_date,
				this._dept_name,
				this._dept_guid,
				this._remark,
				this._plan_hour,
				this._act_hour,
				this._TempTask_code,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "PLN_Tepmtask");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field task_id = new Field("task_id", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field task_guid = new Field("task_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proj_id = new Field("proj_id", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proj_guid = new Field("proj_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wbs_id = new Field("wbs_id", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wbs_guid = new Field("wbs_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 日历
			/// </summary>
			public readonly static Field clndr_id = new Field("clndr_id", "PLN_Tepmtask", "日历");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field clndr_guid = new Field("clndr_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_id = new Field("plan_id", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_guid = new Field("plan_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 排序号
			/// </summary>
			public readonly static Field seq_num = new Field("seq_num", "PLN_Tepmtask", "排序号");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field parent_task_id = new Field("parent_task_id", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field parent_guid = new Field("parent_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 权重
			/// </summary>
			public readonly static Field est_wt = new Field("est_wt", "PLN_Tepmtask", "权重");
			/// <summary>
			/// 完成百分比
			/// </summary>
			public readonly static Field complete_pct = new Field("complete_pct", "PLN_Tepmtask", "完成百分比");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field rev_fdbk_flag = new Field("rev_fdbk_flag", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field lock_plan_flag = new Field("lock_plan_flag", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field auto_compute_act_flag = new Field("auto_compute_act_flag", "PLN_Tepmtask", "");
			/// <summary>
			/// 完成百分比计算类型，原值(&#39;CP_Drtn&#39;)，现改为true为关联步骤，false为不关联
			/// </summary>
			public readonly static Field complete_pct_type = new Field("complete_pct_type", "PLN_Tepmtask", "完成百分比计算类型，原值(&#39;CP_Drtn&#39;)，现改为true为关联步骤，false为不关联");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field task_type = new Field("task_type", "PLN_Tepmtask", "");
			/// <summary>
			/// 工期类型
			/// </summary>
			public readonly static Field duration_type = new Field("duration_type", "PLN_Tepmtask", "工期类型");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field review_type = new Field("review_type", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field status_code = new Field("status_code", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field task_code = new Field("task_code", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field task_name = new Field("task_name", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field rsrc_name = new Field("rsrc_name", "PLN_Tepmtask", "");
			/// <summary>
			/// 资源id
			/// </summary>
			public readonly static Field rsrc_id = new Field("rsrc_id", "PLN_Tepmtask", "资源id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field rsrc_guid = new Field("rsrc_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// TF
			/// </summary>
			public readonly static Field total_float_hr_cnt = new Field("total_float_hr_cnt", "PLN_Tepmtask", "TF");
			/// <summary>
			/// FF
			/// </summary>
			public readonly static Field free_float_hr_cnt = new Field("free_float_hr_cnt", "PLN_Tepmtask", "FF");
			/// <summary>
			/// 原定工期
			/// </summary>
			public readonly static Field target_drtn_hr_cnt = new Field("target_drtn_hr_cnt", "PLN_Tepmtask", "原定工期");
			/// <summary>
			/// 实际工期
			/// </summary>
			public readonly static Field act_drtn_hr_cnt = new Field("act_drtn_hr_cnt", "PLN_Tepmtask", "实际工期");
			/// <summary>
			/// 尚需工期
			/// </summary>
			public readonly static Field remain_drtn_hr_cnt = new Field("remain_drtn_hr_cnt", "PLN_Tepmtask", "尚需工期");
			/// <summary>
			/// 实际工作天数
			/// </summary>
			public readonly static Field act_work_qty = new Field("act_work_qty", "PLN_Tepmtask", "实际工作天数");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field remain_work_qty = new Field("remain_work_qty", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_work_qty = new Field("target_work_qty", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_equip_qty = new Field("target_equip_qty", "PLN_Tepmtask", "");
			/// <summary>
			/// 实际时
			/// </summary>
			public readonly static Field act_equip_qty = new Field("act_equip_qty", "PLN_Tepmtask", "实际时");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field remain_equip_qty = new Field("remain_equip_qty", "PLN_Tepmtask", "");
			/// <summary>
			/// 限制条件1
			/// </summary>
			public readonly static Field cstr_type = new Field("cstr_type", "PLN_Tepmtask", "限制条件1");
			/// <summary>
			/// 限制条件1日期
			/// </summary>
			public readonly static Field cstr_date = new Field("cstr_date", "PLN_Tepmtask", "限制条件1日期");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field late_start_date = new Field("late_start_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field late_end_date = new Field("late_end_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field early_start_date = new Field("early_start_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field early_end_date = new Field("early_end_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field restart_date = new Field("restart_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field reend_date = new Field("reend_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field review_end_date = new Field("review_end_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 尚需 最晚开始时间(逻辑计算相关)
			/// </summary>
			public readonly static Field rem_late_start_date = new Field("rem_late_start_date", "PLN_Tepmtask", "尚需 最晚开始时间(逻辑计算相关)");
			/// <summary>
			/// 尚需 最晚结束时间(逻辑计算相关)
			/// </summary>
			public readonly static Field rem_late_end_date = new Field("rem_late_end_date", "PLN_Tepmtask", "尚需 最晚结束时间(逻辑计算相关)");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field priority_type = new Field("priority_type", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field guid = new Field("guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field tmpl_guid = new Field("tmpl_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 限制条件2日期
			/// </summary>
			public readonly static Field cstr_date2 = new Field("cstr_date2", "PLN_Tepmtask", "限制条件2日期");
			/// <summary>
			/// 限制条件2
			/// </summary>
			public readonly static Field cstr_type2 = new Field("cstr_type2", "PLN_Tepmtask", "限制条件2");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_this_per_work_qty = new Field("act_this_per_work_qty", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_this_per_equip_qty = new Field("act_this_per_equip_qty", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field driving_path_flag = new Field("driving_path_flag", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field float_path = new Field("float_path", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field float_path_order = new Field("float_path_order", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field suspend_date = new Field("suspend_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field resume_date = new Field("resume_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field external_early_start_date = new Field("external_early_start_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field external_late_end_date = new Field("external_late_end_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field update_date = new Field("update_date", "PLN_Tepmtask", "更新时间");
			/// <summary>
			/// 更新人
			/// </summary>
			public readonly static Field update_user = new Field("update_user", "PLN_Tepmtask", "更新人");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field create_date = new Field("create_date", "PLN_Tepmtask", "创建时间");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field create_user_sid = new Field("create_user_sid", "PLN_Tepmtask", "");
			/// <summary>
			/// 创建人
			/// </summary>
			public readonly static Field create_user = new Field("create_user", "PLN_Tepmtask", "创建人");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field delete_session_id = new Field("delete_session_id", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field delete_date = new Field("delete_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_start_date = new Field("act_start_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_end_date = new Field("act_end_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 计划开始
			/// </summary>
			public readonly static Field expect_start_date = new Field("expect_start_date", "PLN_Tepmtask", "计划开始");
			/// <summary>
			/// 计划结束
			/// </summary>
			public readonly static Field expect_end_date = new Field("expect_end_date", "PLN_Tepmtask", "计划结束");
			/// <summary>
			/// 计划开始时间
			/// </summary>
			public readonly static Field target_start_date = new Field("target_start_date", "PLN_Tepmtask", "计划开始时间");
			/// <summary>
			/// 计划结束时间
			/// </summary>
			public readonly static Field target_end_date = new Field("target_end_date", "PLN_Tepmtask", "计划结束时间");
			/// <summary>
			/// 是否是系统生成,不能改变结构的,1是,0否
			/// </summary>
			public readonly static Field SysOrNot = new Field("SysOrNot", "PLN_Tepmtask", "是否是系统生成,不能改变结构的,1是,0否");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field rec_type = new Field("rec_type", "PLN_Tepmtask", "");
			/// <summary>
			/// 从模版对应id
			/// </summary>
			public readonly static Field temp_id = new Field("temp_id", "PLN_Tepmtask", "从模版对应id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field p3ec_flag = new Field("p3ec_flag", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field p3ec_task_id = new Field("p3ec_task_id", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field data_date = new Field("data_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field start_date = new Field("start_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field end_date = new Field("end_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_task_id_befor = new Field("plan_task_id_befor", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_task_guid_before = new Field("plan_task_guid_before", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field memo = new Field("memo", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field module_type = new Field("module_type", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_actvcode_guid = new Field("plan_actvcode_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_actvcode_id = new Field("plan_actvcode_id", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field parent_task_plan_guid = new Field("parent_task_plan_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field est_wt_pct = new Field("est_wt_pct", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field curve_guid = new Field("curve_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field feedback_pct_type = new Field("feedback_pct_type", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field baseline_start_date = new Field("baseline_start_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field baseline_end_date = new Field("baseline_end_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field baseline2_start_date = new Field("baseline2_start_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field baseline2_end_date = new Field("baseline2_end_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field baseline3_start_date = new Field("baseline3_start_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field baseline3_end_date = new Field("baseline3_end_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field progress_rsrc_unit_name = new Field("progress_rsrc_unit_name", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field progress_rsrc_unit_price = new Field("progress_rsrc_unit_price", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_progress_rsrc_cost = new Field("target_progress_rsrc_cost", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_progress_rsrc_cost = new Field("act_progress_rsrc_cost", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field remain_progress_rsrc_cost = new Field("remain_progress_rsrc_cost", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_progress_rsrc_curv = new Field("target_progress_rsrc_curv", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_progress_rsrc_curv = new Field("act_progress_rsrc_curv", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field remain_progress_rsrc_curv = new Field("remain_progress_rsrc_curv", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_progress_rsrc_guid = new Field("target_progress_rsrc_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_progress_rsrc_code = new Field("target_progress_rsrc_code", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_progress_rsrc_qty = new Field("target_progress_rsrc_qty", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_progress_rsrc_qty = new Field("act_progress_rsrc_qty", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field remain_progress_rsrc_qty = new Field("remain_progress_rsrc_qty", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field videoUrl = new Field("videoUrl", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field bcws_cost = new Field("bcws_cost", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field bcwp_cost = new Field("bcwp_cost", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field acwp_cost = new Field("acwp_cost", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field istopbreakdown = new Field("istopbreakdown", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field budget_cost = new Field("budget_cost", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field attach_flag = new Field("attach_flag", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UPDATE_SESSION_ID = new Field("UPDATE_SESSION_ID", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_complete_pct = new Field("target_complete_pct", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field period_target_complete_pct = new Field("period_target_complete_pct", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field important_node_flag = new Field("important_node_flag", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_pct = new Field("plan_pct", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field feedback_data_date = new Field("feedback_data_date", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field dept_name = new Field("dept_name", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field dept_guid = new Field("dept_guid", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field remark = new Field("remark", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_hour = new Field("plan_hour", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_hour = new Field("act_hour", "PLN_Tepmtask", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TempTask_code = new Field("TempTask_code", "PLN_Tepmtask", "");
		}
		#endregion
	}
}