//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace JJWBSService
{
	/// <summary>
	/// 实体类PLN_TASKPRED。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("PLN_TASKPRED")]
	[Serializable]
	[DataContract]
	public partial class PLN_TASKPRED : Entity
	{
		#region Model
		private int _task_pred_id;
		private int _task_id;
		private int? _wbs_id;
		private int _pred_task_id;
		private int? _pred_wbs_id;
		private int _proj_id;
		private int _pred_proj_id;
		private string _pred_type;
		private decimal? _lag_hr_cnt;
		private DateTime? _update_date;
		private string _update_user;
		private DateTime? _create_date;
		private string _create_user;
		private int? _delete_session_id;
		private DateTime? _delete_date;
		private int? _temp_id;
		private int? _p3ec_flag;
		private int? _p3ec_pred_id;
		private string _task_guid;
		private string _pred_guid;
		private string _control_path_flag;
		private int? _plan_id;
		private int? _pred_plan_id;
		private string _task_pred_guid;
		private string _wbs_guid;
		private string _pred_wbs_guid;
		private string _proj_guid;
		private string _plan_guid;
		private string _pred_proj_guid;
		private string _pred_plan_guid;
		private string _temp_guid;

		/// <summary>
		/// 
		/// </summary>
		[Field("task_pred_id")]
		[DataMember]
		public int task_pred_id
		{
			get { return _task_pred_id; }
			set
			{
				this.OnPropertyValueChange("task_pred_id");
				this._task_pred_id = value;
			}
		}
		/// <summary>
		/// 当前taskid
		/// </summary>
		[Field("task_id")]
		[DataMember]
		public int task_id
		{
			get { return _task_id; }
			set
			{
				this.OnPropertyValueChange("task_id");
				this._task_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("wbs_id")]
		[DataMember]
		public int? wbs_id
		{
			get { return _wbs_id; }
			set
			{
				this.OnPropertyValueChange("wbs_id");
				this._wbs_id = value;
			}
		}
		/// <summary>
		/// 紧前taskid
		/// </summary>
		[Field("pred_task_id")]
		[DataMember]
		public int pred_task_id
		{
			get { return _pred_task_id; }
			set
			{
				this.OnPropertyValueChange("pred_task_id");
				this._pred_task_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("pred_wbs_id")]
		[DataMember]
		public int? pred_wbs_id
		{
			get { return _pred_wbs_id; }
			set
			{
				this.OnPropertyValueChange("pred_wbs_id");
				this._pred_wbs_id = value;
			}
		}
		/// <summary>
		/// 项目id
		/// </summary>
		[Field("proj_id")]
		[DataMember]
		public int proj_id
		{
			get { return _proj_id; }
			set
			{
				this.OnPropertyValueChange("proj_id");
				this._proj_id = value;
			}
		}
		/// <summary>
		/// 紧前项目id
		/// </summary>
		[Field("pred_proj_id")]
		[DataMember]
		public int pred_proj_id
		{
			get { return _pred_proj_id; }
			set
			{
				this.OnPropertyValueChange("pred_proj_id");
				this._pred_proj_id = value;
			}
		}
		/// <summary>
		/// 关系类型，现均为FS
		/// </summary>
		[Field("pred_type")]
		[DataMember]
		public string pred_type
		{
			get { return _pred_type; }
			set
			{
				this.OnPropertyValueChange("pred_type");
				this._pred_type = value;
			}
		}
		/// <summary>
		/// 浮时
		/// </summary>
		[Field("lag_hr_cnt")]
		[DataMember]
		public decimal? lag_hr_cnt
		{
			get { return _lag_hr_cnt; }
			set
			{
				this.OnPropertyValueChange("lag_hr_cnt");
				this._lag_hr_cnt = value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		[Field("update_date")]
		[DataMember]
		public DateTime? update_date
		{
			get { return _update_date; }
			set
			{
				this.OnPropertyValueChange("update_date");
				this._update_date = value;
			}
		}
		/// <summary>
		/// 更新人员
		/// </summary>
		[Field("update_user")]
		[DataMember]
		public string update_user
		{
			get { return _update_user; }
			set
			{
				this.OnPropertyValueChange("update_user");
				this._update_user = value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		[Field("create_date")]
		[DataMember]
		public DateTime? create_date
		{
			get { return _create_date; }
			set
			{
				this.OnPropertyValueChange("create_date");
				this._create_date = value;
			}
		}
		/// <summary>
		/// 创建人员
		/// </summary>
		[Field("create_user")]
		[DataMember]
		public string create_user
		{
			get { return _create_user; }
			set
			{
				this.OnPropertyValueChange("create_user");
				this._create_user = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("delete_session_id")]
		[DataMember]
		public int? delete_session_id
		{
			get { return _delete_session_id; }
			set
			{
				this.OnPropertyValueChange("delete_session_id");
				this._delete_session_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("delete_date")]
		[DataMember]
		public DateTime? delete_date
		{
			get { return _delete_date; }
			set
			{
				this.OnPropertyValueChange("delete_date");
				this._delete_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("temp_id")]
		[DataMember]
		public int? temp_id
		{
			get { return _temp_id; }
			set
			{
				this.OnPropertyValueChange("temp_id");
				this._temp_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("p3ec_flag")]
		[DataMember]
		public int? p3ec_flag
		{
			get { return _p3ec_flag; }
			set
			{
				this.OnPropertyValueChange("p3ec_flag");
				this._p3ec_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("p3ec_pred_id")]
		[DataMember]
		public int? p3ec_pred_id
		{
			get { return _p3ec_pred_id; }
			set
			{
				this.OnPropertyValueChange("p3ec_pred_id");
				this._p3ec_pred_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("task_guid")]
		[DataMember]
		public string task_guid
		{
			get { return _task_guid; }
			set
			{
				this.OnPropertyValueChange("task_guid");
				this._task_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("pred_guid")]
		[DataMember]
		public string pred_guid
		{
			get { return _pred_guid; }
			set
			{
				this.OnPropertyValueChange("pred_guid");
				this._pred_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("control_path_flag")]
		[DataMember]
		public string control_path_flag
		{
			get { return _control_path_flag; }
			set
			{
				this.OnPropertyValueChange("control_path_flag");
				this._control_path_flag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_id")]
		[DataMember]
		public int? plan_id
		{
			get { return _plan_id; }
			set
			{
				this.OnPropertyValueChange("plan_id");
				this._plan_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("pred_plan_id")]
		[DataMember]
		public int? pred_plan_id
		{
			get { return _pred_plan_id; }
			set
			{
				this.OnPropertyValueChange("pred_plan_id");
				this._pred_plan_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("task_pred_guid")]
		[DataMember]
		public string task_pred_guid
		{
			get { return _task_pred_guid; }
			set
			{
				this.OnPropertyValueChange("task_pred_guid");
				this._task_pred_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("wbs_guid")]
		[DataMember]
		public string wbs_guid
		{
			get { return _wbs_guid; }
			set
			{
				this.OnPropertyValueChange("wbs_guid");
				this._wbs_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("pred_wbs_guid")]
		[DataMember]
		public string pred_wbs_guid
		{
			get { return _pred_wbs_guid; }
			set
			{
				this.OnPropertyValueChange("pred_wbs_guid");
				this._pred_wbs_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proj_guid")]
		[DataMember]
		public string proj_guid
		{
			get { return _proj_guid; }
			set
			{
				this.OnPropertyValueChange("proj_guid");
				this._proj_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_guid")]
		[DataMember]
		public string plan_guid
		{
			get { return _plan_guid; }
			set
			{
				this.OnPropertyValueChange("plan_guid");
				this._plan_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("pred_proj_guid")]
		[DataMember]
		public string pred_proj_guid
		{
			get { return _pred_proj_guid; }
			set
			{
				this.OnPropertyValueChange("pred_proj_guid");
				this._pred_proj_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("pred_plan_guid")]
		[DataMember]
		public string pred_plan_guid
		{
			get { return _pred_plan_guid; }
			set
			{
				this.OnPropertyValueChange("pred_plan_guid");
				this._pred_plan_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("temp_guid")]
		[DataMember]
		public string temp_guid
		{
			get { return _temp_guid; }
			set
			{
				this.OnPropertyValueChange("temp_guid");
				this._temp_guid = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.task_pred_id,
				_.task_pred_guid,
			};
		}
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.task_pred_id;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.task_pred_id,
				_.task_id,
				_.wbs_id,
				_.pred_task_id,
				_.pred_wbs_id,
				_.proj_id,
				_.pred_proj_id,
				_.pred_type,
				_.lag_hr_cnt,
				_.update_date,
				_.update_user,
				_.create_date,
				_.create_user,
				_.delete_session_id,
				_.delete_date,
				_.temp_id,
				_.p3ec_flag,
				_.p3ec_pred_id,
				_.task_guid,
				_.pred_guid,
				_.control_path_flag,
				_.plan_id,
				_.pred_plan_id,
				_.task_pred_guid,
				_.wbs_guid,
				_.pred_wbs_guid,
				_.proj_guid,
				_.plan_guid,
				_.pred_proj_guid,
				_.pred_plan_guid,
				_.temp_guid,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._task_pred_id,
				this._task_id,
				this._wbs_id,
				this._pred_task_id,
				this._pred_wbs_id,
				this._proj_id,
				this._pred_proj_id,
				this._pred_type,
				this._lag_hr_cnt,
				this._update_date,
				this._update_user,
				this._create_date,
				this._create_user,
				this._delete_session_id,
				this._delete_date,
				this._temp_id,
				this._p3ec_flag,
				this._p3ec_pred_id,
				this._task_guid,
				this._pred_guid,
				this._control_path_flag,
				this._plan_id,
				this._pred_plan_id,
				this._task_pred_guid,
				this._wbs_guid,
				this._pred_wbs_guid,
				this._proj_guid,
				this._plan_guid,
				this._pred_proj_guid,
				this._pred_plan_guid,
				this._temp_guid,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "PLN_TASKPRED");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field task_pred_id = new Field("task_pred_id", "PLN_TASKPRED", "");
			/// <summary>
			/// 当前taskid
			/// </summary>
			public readonly static Field task_id = new Field("task_id", "PLN_TASKPRED", "当前taskid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wbs_id = new Field("wbs_id", "PLN_TASKPRED", "");
			/// <summary>
			/// 紧前taskid
			/// </summary>
			public readonly static Field pred_task_id = new Field("pred_task_id", "PLN_TASKPRED", "紧前taskid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field pred_wbs_id = new Field("pred_wbs_id", "PLN_TASKPRED", "");
			/// <summary>
			/// 项目id
			/// </summary>
			public readonly static Field proj_id = new Field("proj_id", "PLN_TASKPRED", "项目id");
			/// <summary>
			/// 紧前项目id
			/// </summary>
			public readonly static Field pred_proj_id = new Field("pred_proj_id", "PLN_TASKPRED", "紧前项目id");
			/// <summary>
			/// 关系类型，现均为FS
			/// </summary>
			public readonly static Field pred_type = new Field("pred_type", "PLN_TASKPRED", "关系类型，现均为FS");
			/// <summary>
			/// 浮时
			/// </summary>
			public readonly static Field lag_hr_cnt = new Field("lag_hr_cnt", "PLN_TASKPRED", "浮时");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field update_date = new Field("update_date", "PLN_TASKPRED", "更新时间");
			/// <summary>
			/// 更新人员
			/// </summary>
			public readonly static Field update_user = new Field("update_user", "PLN_TASKPRED", "更新人员");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field create_date = new Field("create_date", "PLN_TASKPRED", "创建时间");
			/// <summary>
			/// 创建人员
			/// </summary>
			public readonly static Field create_user = new Field("create_user", "PLN_TASKPRED", "创建人员");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field delete_session_id = new Field("delete_session_id", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field delete_date = new Field("delete_date", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field temp_id = new Field("temp_id", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field p3ec_flag = new Field("p3ec_flag", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field p3ec_pred_id = new Field("p3ec_pred_id", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field task_guid = new Field("task_guid", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field pred_guid = new Field("pred_guid", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field control_path_flag = new Field("control_path_flag", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_id = new Field("plan_id", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field pred_plan_id = new Field("pred_plan_id", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field task_pred_guid = new Field("task_pred_guid", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wbs_guid = new Field("wbs_guid", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field pred_wbs_guid = new Field("pred_wbs_guid", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proj_guid = new Field("proj_guid", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_guid = new Field("plan_guid", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field pred_proj_guid = new Field("pred_proj_guid", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field pred_plan_guid = new Field("pred_plan_guid", "PLN_TASKPRED", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field temp_guid = new Field("temp_guid", "PLN_TASKPRED", "");
		}
		#endregion
	}
}