//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace JJWBSService.Modes
{
	/// <summary>
	/// 实体类PS_PLN_TaskBCWS。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("PS_PLN_TaskBCWS")]
	[Serializable]
	public partial class PS_PLN_TaskBCWS : Entity
	{
		#region Model
		private Guid _Id;
		private Guid? _period_guid;
		private DateTime? _periodstrat;
		private DateTime? _periodend;
		private string _type;
		private Guid? _task_guid;
		private float? _est_wt_pct;
		private float? _plan_complete_pct;
		private Guid? _rsrc_guid;
		private string _rsrc_name;
		private float? _period_value;
		private Guid? _plan_guid;
		private float? _act_complete_pct;
		private float? _act_value;
		private float? _period_complete_pct;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public Guid Id
		{
			get { return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("period_guid")]
		public Guid? period_guid
		{
			get { return _period_guid; }
			set
			{
				this.OnPropertyValueChange("period_guid");
				this._period_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("periodstrat")]
		public DateTime? periodstrat
		{
			get { return _periodstrat; }
			set
			{
				this.OnPropertyValueChange("periodstrat");
				this._periodstrat = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("periodend")]
		public DateTime? periodend
		{
			get { return _periodend; }
			set
			{
				this.OnPropertyValueChange("periodend");
				this._periodend = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("type")]
		public string type
		{
			get { return _type; }
			set
			{
				this.OnPropertyValueChange("type");
				this._type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("task_guid")]
		public Guid? task_guid
		{
			get { return _task_guid; }
			set
			{
				this.OnPropertyValueChange("task_guid");
				this._task_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("est_wt_pct")]
		public float? est_wt_pct
		{
			get { return _est_wt_pct; }
			set
			{
				this.OnPropertyValueChange("est_wt_pct");
				this._est_wt_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_complete_pct")]
		public float? plan_complete_pct
		{
			get { return _plan_complete_pct; }
			set
			{
				this.OnPropertyValueChange("plan_complete_pct");
				this._plan_complete_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("rsrc_guid")]
		public Guid? rsrc_guid
		{
			get { return _rsrc_guid; }
			set
			{
				this.OnPropertyValueChange("rsrc_guid");
				this._rsrc_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("rsrc_name")]
		public string rsrc_name
		{
			get { return _rsrc_name; }
			set
			{
				this.OnPropertyValueChange("rsrc_name");
				this._rsrc_name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("period_value")]
		public float? period_value
		{
			get { return _period_value; }
			set
			{
				this.OnPropertyValueChange("period_value");
				this._period_value = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_guid")]
		public Guid? plan_guid
		{
			get { return _plan_guid; }
			set
			{
				this.OnPropertyValueChange("plan_guid");
				this._plan_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_complete_pct")]
		public float? act_complete_pct
		{
			get { return _act_complete_pct; }
			set
			{
				this.OnPropertyValueChange("act_complete_pct");
				this._act_complete_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_value")]
		public float? act_value
		{
			get { return _act_value; }
			set
			{
				this.OnPropertyValueChange("act_value");
				this._act_value = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("period_complete_pct")]
		public float? period_complete_pct
		{
			get { return _period_complete_pct; }
			set
			{
				this.OnPropertyValueChange("period_complete_pct");
				this._period_complete_pct = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.period_guid,
				_.periodstrat,
				_.periodend,
				_.type,
				_.task_guid,
				_.est_wt_pct,
				_.plan_complete_pct,
				_.rsrc_guid,
				_.rsrc_name,
				_.period_value,
				_.plan_guid,
				_.act_complete_pct,
				_.act_value,
				_.period_complete_pct,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._period_guid,
				this._periodstrat,
				this._periodend,
				this._type,
				this._task_guid,
				this._est_wt_pct,
				this._plan_complete_pct,
				this._rsrc_guid,
				this._rsrc_name,
				this._period_value,
				this._plan_guid,
				this._act_complete_pct,
				this._act_value,
				this._period_complete_pct,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "PS_PLN_TaskBCWS");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field period_guid = new Field("period_guid", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field periodstrat = new Field("periodstrat", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field periodend = new Field("periodend", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field type = new Field("type", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field task_guid = new Field("task_guid", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field est_wt_pct = new Field("est_wt_pct", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_complete_pct = new Field("plan_complete_pct", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field rsrc_guid = new Field("rsrc_guid", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field rsrc_name = new Field("rsrc_name", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field period_value = new Field("period_value", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_guid = new Field("plan_guid", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_complete_pct = new Field("act_complete_pct", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_value = new Field("act_value", "PS_PLN_TaskBCWS", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field period_complete_pct = new Field("period_complete_pct", "PS_PLN_TaskBCWS", "");
		}
		#endregion
	}
}