//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace JJWBSService.Modes
{
	/// <summary>
	/// 实体类PS_PLN_TaskProc_Sub。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("PS_PLN_TaskProc_Sub")]
	[Serializable]
	[DataContract]
	public partial class PS_PLN_TaskProc_Sub : Entity
	{
		#region Model
		private string _ProcSub_guid;
		private string _ProcSub_Name;
		private string _proj_guid;
		private string _plan_guid;
		private string _wbs_guid;
		private string _task_guid;
		private string _proc_guid;
		private int? _seq_num;
		private int? _est_wt;
		private float? _est_wt_pct;
		private decimal? _complete_pct;
		private DateTime? _target_end_date;
		private DateTime? _act_end_date;
		private string _temp_guid;
		private string _remark;
		private DateTime? _RegDate;
		private string _RegHumName;
		private Guid? _RegHumId;
		private Guid? _UpdHumId;
		private string _UpdHuman;
		private DateTime? _UpdDate;
		private DateTime? _CheckDate;
		private string _SubState;
		private DateTime? _CompleteDate;
		private string _ProcSub_Code;

		/// <summary>
		/// 
		/// </summary>
		[Field("ProcSub_guid")]
		[DataMember]
		public string ProcSub_guid
		{
			get { return _ProcSub_guid; }
			set
			{
				this.OnPropertyValueChange("ProcSub_guid");
				this._ProcSub_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ProcSub_Name")]
		[DataMember]
		public string ProcSub_Name
		{
			get { return _ProcSub_Name; }
			set
			{
				this.OnPropertyValueChange("ProcSub_Name");
				this._ProcSub_Name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proj_guid")]
		[DataMember]
		public string proj_guid
		{
			get { return _proj_guid; }
			set
			{
				this.OnPropertyValueChange("proj_guid");
				this._proj_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("plan_guid")]
		[DataMember]
		public string plan_guid
		{
			get { return _plan_guid; }
			set
			{
				this.OnPropertyValueChange("plan_guid");
				this._plan_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("wbs_guid")]
		[DataMember]
		public string wbs_guid
		{
			get { return _wbs_guid; }
			set
			{
				this.OnPropertyValueChange("wbs_guid");
				this._wbs_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("task_guid")]
		[DataMember]
		public string task_guid
		{
			get { return _task_guid; }
			set
			{
				this.OnPropertyValueChange("task_guid");
				this._task_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("proc_guid")]
		[DataMember]
		public string proc_guid
		{
			get { return _proc_guid; }
			set
			{
				this.OnPropertyValueChange("proc_guid");
				this._proc_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("seq_num")]
		[DataMember]
		public int? seq_num
		{
			get { return _seq_num; }
			set
			{
				this.OnPropertyValueChange("seq_num");
				this._seq_num = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("est_wt")]
		[DataMember]
		public int? est_wt
		{
			get { return _est_wt; }
			set
			{
				this.OnPropertyValueChange("est_wt");
				this._est_wt = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("est_wt_pct")]
		[DataMember]
		public float? est_wt_pct
		{
			get { return _est_wt_pct; }
			set
			{
				this.OnPropertyValueChange("est_wt_pct");
				this._est_wt_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("complete_pct")]
		[DataMember]
		public decimal? complete_pct
		{
			get { return _complete_pct; }
			set
			{
				this.OnPropertyValueChange("complete_pct");
				this._complete_pct = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("target_end_date")]
		[DataMember]
		public DateTime? target_end_date
		{
			get { return _target_end_date; }
			set
			{
				this.OnPropertyValueChange("target_end_date");
				this._target_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("act_end_date")]
		[DataMember]
		public DateTime? act_end_date
		{
			get { return _act_end_date; }
			set
			{
				this.OnPropertyValueChange("act_end_date");
				this._act_end_date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("temp_guid")]
		[DataMember]
		public string temp_guid
		{
			get { return _temp_guid; }
			set
			{
				this.OnPropertyValueChange("temp_guid");
				this._temp_guid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("remark")]
		[DataMember]
		public string remark
		{
			get { return _remark; }
			set
			{
				this.OnPropertyValueChange("remark");
				this._remark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegDate")]
		[DataMember]
		public DateTime? RegDate
		{
			get { return _RegDate; }
			set
			{
				this.OnPropertyValueChange("RegDate");
				this._RegDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegHumName")]
		[DataMember]
		public string RegHumName
		{
			get { return _RegHumName; }
			set
			{
				this.OnPropertyValueChange("RegHumName");
				this._RegHumName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegHumId")]
		[DataMember]
		public Guid? RegHumId
		{
			get { return _RegHumId; }
			set
			{
				this.OnPropertyValueChange("RegHumId");
				this._RegHumId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UpdHumId")]
		[DataMember]
		public Guid? UpdHumId
		{
			get { return _UpdHumId; }
			set
			{
				this.OnPropertyValueChange("UpdHumId");
				this._UpdHumId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UpdHuman")]
		[DataMember]
		public string UpdHuman
		{
			get { return _UpdHuman; }
			set
			{
				this.OnPropertyValueChange("UpdHuman");
				this._UpdHuman = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UpdDate")]
		[DataMember]
		public DateTime? UpdDate
		{
			get { return _UpdDate; }
			set
			{
				this.OnPropertyValueChange("UpdDate");
				this._UpdDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CheckDate")]
		[DataMember]
		public DateTime? CheckDate
		{
			get { return _CheckDate; }
			set
			{
				this.OnPropertyValueChange("CheckDate");
				this._CheckDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SubState")]
		[DataMember]
		public string SubState
		{
			get { return _SubState; }
			set
			{
				this.OnPropertyValueChange("SubState");
				this._SubState = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CompleteDate")]
		[DataMember]
		public DateTime? CompleteDate
		{
			get { return _CompleteDate; }
			set
			{
				this.OnPropertyValueChange("CompleteDate");
				this._CompleteDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ProcSub_Code")]
		[DataMember]
		public string ProcSub_Code
		{
			get { return _ProcSub_Code; }
			set
			{
				this.OnPropertyValueChange("ProcSub_Code");
				this._ProcSub_Code = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ProcSub_guid,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ProcSub_guid,
				_.ProcSub_Name,
				_.proj_guid,
				_.plan_guid,
				_.wbs_guid,
				_.task_guid,
				_.proc_guid,
				_.seq_num,
				_.est_wt,
				_.est_wt_pct,
				_.complete_pct,
				_.target_end_date,
				_.act_end_date,
				_.temp_guid,
				_.remark,
				_.RegDate,
				_.RegHumName,
				_.RegHumId,
				_.UpdHumId,
				_.UpdHuman,
				_.UpdDate,
				_.CheckDate,
				_.SubState,
				_.CompleteDate,
				_.ProcSub_Code,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ProcSub_guid,
				this._ProcSub_Name,
				this._proj_guid,
				this._plan_guid,
				this._wbs_guid,
				this._task_guid,
				this._proc_guid,
				this._seq_num,
				this._est_wt,
				this._est_wt_pct,
				this._complete_pct,
				this._target_end_date,
				this._act_end_date,
				this._temp_guid,
				this._remark,
				this._RegDate,
				this._RegHumName,
				this._RegHumId,
				this._UpdHumId,
				this._UpdHuman,
				this._UpdDate,
				this._CheckDate,
				this._SubState,
				this._CompleteDate,
				this._ProcSub_Code,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "PS_PLN_TaskProc_Sub");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ProcSub_guid = new Field("ProcSub_guid", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ProcSub_Name = new Field("ProcSub_Name", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proj_guid = new Field("proj_guid", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field plan_guid = new Field("plan_guid", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field wbs_guid = new Field("wbs_guid", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field task_guid = new Field("task_guid", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field proc_guid = new Field("proc_guid", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field seq_num = new Field("seq_num", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field est_wt = new Field("est_wt", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field est_wt_pct = new Field("est_wt_pct", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field complete_pct = new Field("complete_pct", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field target_end_date = new Field("target_end_date", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field act_end_date = new Field("act_end_date", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field temp_guid = new Field("temp_guid", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field remark = new Field("remark", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RegDate = new Field("RegDate", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RegHumName = new Field("RegHumName", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RegHumId = new Field("RegHumId", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdHumId = new Field("UpdHumId", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdHuman = new Field("UpdHuman", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdDate = new Field("UpdDate", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CheckDate = new Field("CheckDate", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SubState = new Field("SubState", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompleteDate = new Field("CompleteDate", "PS_PLN_TaskProc_Sub", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ProcSub_Code = new Field("ProcSub_Code", "PS_PLN_TaskProc_Sub", "");
		}
		#endregion
	}
}